window['okx_web_navigation_header_footer'] = 
{
    "nav_discover_dropdowntitle_markets": "Markten",
    "nav_dex_header_products": "Product",
    "nav_nav_institutions_desc_block": "OTC-liquiditeitsnetwerk voor professionele en institutionele handelaren",
    "commonall_dropdown_text_other": "Overig",
    "nav_desc_easily_enter_options_trading": "Profiteer van marktvolatiliteit met opties",
    "commonall_emptystate_text_no_data": "Geen gegevens beschikbaar",
    "nav_dex_header_portfolio": "Portfolio",
    "commonall_enterfield_title_name": "Naam",
    "tr_nav_footer_text_kep": "KEP-adres (Aangetekende elektronische post): okxteknoloji@hs01.kep.tr",
    "commonall_text_title_time": "Tijd",
    "nav_compliance_variable_verify_by_date_nocaps": "verifieer je identiteit",
    "commonall_enterfield_title_address": "Adres",
    "commonall_btn_title_contact_us": "Contact met ons opnemen",
    "nav_pc_client_upgrade_title": "Herinnering voor updates",
    "commonall_status_text_expired": "Vervallen",
    "nav_web3_header_settings_item_color_preferences": "Kleurvoorkeuren",
    "nav_cex_home_rewards": "Beloningen",
    "nav_more_dropdowntitle_products1": "Producten",
    "nav_nav_institutions_dropdowntitle_api": "API's",
    "commonall_column_colheader_rank": "Positie",
    "nav_pop_tab_select_language": "Taal",
    "nav_web3_header_nav_option_xlayer": "X Layer",
    "nav_country_banner_button": "Site overschakelen",
    "commonall_datetime_abbr_hour": "u",
    "nav_more_dropdowntitle_blockdream_ventures": "OKX Ventures",
    "nav_web3_header_nav_option_learn": "Learn",
    "nav_dex_clipboard_legal_disclaimer": "Disclaimer: Om je te helpen sneller tokens te vinden, kan OKX Wallet automatisch contractadressen detecteren vanuit je klembord. We verwerken deze gegevens alleen lokaal op je apparaat om je tokengegevens te laten zien. Je kunt deze toestemming op elk moment beheren in je Instellingen. Alle getoonde tokeninformatie vormt nadrukkelijk geen aanbod, uitnodiging of aanbeveling om in producten te handelen en geldt niet als financieel of beleggingsadvies.",
    "nav_more_dropdowntitle_vip": "VIP-programma",
    "commonall_tag_text_fixed": "Vast",
    "commonall_enterfield_btn_deposit": "Storten",
    "tr_nav_header_dropdown_desc_transfer_crypto_to_others": "Boek crypto over naar wallets of accounts op andere platforms",
    "nav_finance_loan_subtitle_desc": "Leen om te verdienen, leen om uit te geven",
    "nav_menu_btn_download_qrcode_alt": "QR-code om de OKX-mobiele app te downloaden",
    "commonall_enterfield_title_to": "Naar",
    "nav_popup_title_web3_wallet_singapore": "Welkom bij OKX Wallet",
    "nav_nav_help_alt": "Krijg hulp of volg onze sociale media",
    "nav_language_alert_global_version_var": "globale versie",
    "nav_dex_header_watchlist": "Tracker",
    "nav_uk_risk_warning_footer_btn_done": "Klaar",
    "nav_restrictedproduct_error_title": "Dit product is momenteel niet beschikbaar",
    "nav_nav_institutions_dropdowntitle_home": "Startpagina voor bedrijven",
    "nav_dex_dropdown_tooltip_x_content": "Vertaal de voorbeeld-inhoud van X automatisch naar je plaatselijke taal.",
    "nav_boost_desc_xcampaign": "Doe mee en win aantrekkelijke beloningen",
    "nav_tr_btn1_cancel": "Annuleren",
    "commonall_enterfield_text_please_enter": "Alsjeblieft invoeren",
    "commonall_emptystate_text_page_500_button": "OKX-app downloaden",
    "nav_nav_grow": "Grow",
    "nav_okxalert_dns_btn_installed": "Al geïnstalleerd (niet meer weergeven)",
    "nav_trade_request_for_quote_desc": "Aangepaste strategieën uit meerdere delen en blokhandelstransacties",
    "nav_explorer_main_header_emptystate_loading_failed": "Kan niet worden geladen. Probeer het later nog eens.",
    "commonall_btn_text_try_again": "Opnieuw proberen",
    "nav_web3_header_nav_textbtn_lean_more": "Meer informatie",
    "trade_optionsmarket_select_desc_advanced_options": "Stelk je handelsstrategieën in op de optieketen",
    "nav_okxalert_dns_subtitle_desc": "Je bekijkt een OKX alternatief domein. We raden de volgende twee methoden aan voor een stabiele en soepele gebruikservaring:",
    "nav_dex_clipboard_popup_cta_enable_now": "Inschakelen",
    "commonall_filter_title_transactions": "Transacties",
    "nav_avatar_dropdown_preferences": "Voorkeuren",
    "commonall_resultpage_toast_canceled": "Geannuleerd",
    "commonall_filter_title_history": "Geschiedenis",
    "nav_trade_dropdowntitle_convert": "Converteren",
    "nav_language_title_global": "Wereldwijd",
    "nav_cex_desc_depositfiat": "Voeg geld toe aan je accountsaldo via een bankoverschrijving om te handelen",
    "commonall_emptystate_text_no_results": "Geen resultaten gevonden",
    "nav_okxalert_dns_btn_confirm": "Ik heb dit voltooid. Geen aanwijzingen meer",
    "commonall_modal_btn_connect_wallet": "Portemonnee verbinden",
    "commonall_enterfield_toast_canceled": "Geannuleerd",
    "commonall_colheader_text_txn_hash": "Txn-hash",
    "commonall_resultpage_btn_save": "Opslaan",
    "nav_restrictedproduct_btn_signup": "Aanmelden",
    "nav_trade_dropdowntitle_trading_bot": "Handelsbots",
    "commonall_search_fieldtext_search": "Zoeken",
    "nav_country_banner_button_br": "Trocar de site",
    "commonall_enterfield_title_email": "E-mail",
    "commonall_enterfield_btn_refresh": "Vernieuwen",
    "nav_build_header_title_okx_build": "Wallet API",
    "nav_web3_header_settings_title_color_palette": "Kleurenpalet",
    "nav_view_home_nav_support_title": "Ondersteuning",
    "commonall_colheader_text_operator": "Operator",
    "nav_language_search_placeholder_search": "Zoek",
    "commonall_enterfield_btn_verify": "Verifiëren",
    "commonall_button_btn_submit": "Indienen",
    "nav_finance_dropdowntitle_loan": "Lening",
    "commonall_column_tab_available": "Beschikbaar",
    "nav_okxalert_dns_title_slow_network_download": "We hebben een onstabiel netwerk gedetecteerd. Met OKX voor je desktop kun je sneller en betrouwbaarder handelen.",
    "nav_finance_earn_subtitle_desc": "HODL niet alleen. Earn",
    "commonall_btn_text_transfer": "Overschrijving",
    "trade_optionsmarket_cell_desc_simple_options_two": "Ga aan de slag met beginnersvriendelijke optiehandel",
    "nav_dex_dropdown_clipboard_status_disabled": "Uitgeschakeld",
    "nav_restrictedproduct_error_bodyprelogin": "Dit product is niet verkrijgbaar in {country} vanwege lokale wet- en regelgeving. Als je niet in {country} woont, log dan in of meld je aan om toegang te krijgen tot deze pagina.",
    "nav_dropdowntitle_my_request": "Mijn tickets",
    "nav_web3_header_nav_option_xlayer_hackathon": "X Layer AI Hackathon",
    "nav_build_header_title_eco_hub": "Eco Hub",
    "commonall_tag_text_flexible": "Flexibel",
    "nav_institutional_loan_entry_subheader": "Loans with fixed terms to power your boldest capital goals",
    "commonall_resultpage_tag_failed": "Mislukt",
    "nav_trade_dropdowntitle_margin_trading": "Derivaten en margehandel",
    "nav_institutional_loan_entry_header": "VIP Loan",
    "nav_option_futures": "Futures",
    "commonall_button_title_faq": "Veelgestelde vragen",
    "commonall_title_item_text_withdrawal": "Opname",
    "navdropdown_header_title_getting_started": "Aan de slag",
    "commonall_emptystate_text_page_404_button": "Ga naar de startpagina",
    "nav_slogan_trade_with_okx": "Handel vanaf je mobiele telefoon met OKX",
    "commonall_colheader_title_amount": "Bedrag",
    "nav_main_navigation_menu_alt": "Hoofdmenu",
    "commonall_emptystate_text_try_again": "Opnieuw proberen",
    "nav_language_title_united_states": "Verenigde Staten",
    "nav_web3_header_nav_option_dexapi_docs": "API-documentatie",
    "nav_okalert_footer_ip_btn_close": "Sluiten",
    "nav_pre_market_trading": "Pre-markt perpetuals",
    "nav_pop_tab_exchange_rate": "Valuta",
    "commonall_btn_title_filter": "Filteren",
    "commonall_text_btn_confirm": "Bevestigen",
    "commonall_modal_btn_approve": "Goedkeuren",
    "nav_web3_header_nav_option_dev_docs": "Documentatie voor ontwikkelaars",
    "commonall_modal_label_available_balance": "Beschikbaar saldo",
    "commonall_filter_btn_deposit": "Storten",
    "navdropdown_header_title_blog": "Blog",
    "nav_okx_community_page_alt": "De community pagina en socials van OKX",
    "commonall_resultpage_btn_edit": "Bewerken",
    "nav_more_dropdowntitle_others3": "Anders",
    "nav_nav_institutions_desc_data": "Kaarsgrafieken, totaalcijfers voor transacties, orderboekgegevens en meer",
    "nav_language_alert_viewing_region": "Je bekijkt de versie van de website voor {region}.",
    "nav_more_dropdowntitle_tradingview": "Handel op TradingView",
    "nav_banner_dialog_title_country_content_br": "Parece que você está no Brasil",
    "commonall_resultpage_button_verifying_task": "Verifying",
    "nav_language_title_brazil": "Brazilië",
    "commonall_filter_dropdown_trade": "Handelen",
    "nav_account_item_country_region": "Land/regio",
    "nav_dexreferral_landing_nav_header_referral": "Referral",
    "commonall_colheader_text_token": "Token",
    "nav_trade_dropdowntitle_nitro": "Nitro Spreads",
    "commonall_filter_dropdown_custom": "Aangepast",
    "nav_language_reminder_your_lang_selection": "Je taalkeuze is van toepassing op OKX-e-mails, sms-berichten en in-app meldingen, evenals alle apparaten waarop je bent ingelogd",
    "nav_dialog_btn_cont": "Doorgaan",
    "nav_au_homepage_nav_products_responsibility_report": "Verantwoordelijkheidsrapport",
    "nav_assets_dropdown_transfer1": "Overschrijving",
    "nav_explorer_tracker_homepage_common_explorer_new": "Nieuw",
    "nav_web3_header_settings_desc_color_classic": "Klassiek",
    "commonall_emptystate_text_page_404_subtitle": "We konden niet vinden wat je zocht, maar op onze homepage vind je wel wat je zoekt.",
    "commonall_text_btn_share_discord": "Discord",
    "nav_finance_jumpstar_subtitle_desc": "Ontdek nieuwe projecten van hoge kwaliteit over de hele wereld",
    "navdropdown_header_textarea_read_stories": "Lees inzichten en verhalen van ons team",
    "commonall_emptystate_text_no_records": "Geen records gevonden",
    "nav_web3_header_nav_btn_android": "Android",
    "commonall_enterfield_title_currency": "Valuta",
    "swaptrade_error_amount_cannot_be_empty_or_zero": "Het bedrag moet meer zijn dan 0.",
    "nav_hk_bottom_toast_okx_not_available_describe_url": "aangekondigd",
    "nav_boost_title_rewards_center": "Beloningscentrum",
    "nav_trade_dropdowntitle_rfq": "Prijsaanvraag (RFQ)",
    "nav_compliance_variable_verify_resume_caps": "Verifieer je identiteit",
    "commonall_modal_title_overview": "Overzicht",
    "commonall_text_btn_view_details": "Details weergeven",
    "nav_nav_trade": "Handelen",
    "nav_perpetual_mid_modaldesc_region_unavailable_all": "OKX Web3 afgeleide producten zijn niet beschikbaar in {country}. Je hebt nog steeds toegang tot andere functies van OKX Wallet.",
    "nav_nav_bell_alt": "Meldingen en aankondigingen",
    "tr_nav_header_dropdown_desc_send_try_quickly": "Stuur snel TRY naar bankrekeningen",
    "commonall_filter_title_price": "Prijs",
    "nav_dialog_close_gotowallet": "Dit niet meer weergeven",
    "commonall_modal_btn_subscribe": "Abonneren",
    "nav_nav_institutions_desc_home": "Het krachtigste pakket oplossingen voor cryptohandel ter wereld",
    "commonall_datetime_abbr_second": "s",
    "commonall_enterfield_btn_close": "Sluiten",
    "commonall_colheader_text_to": "Naar",
    "commonall_column_tab_pnl": "PnL%",
    "nav_nav_discover": "Ontdekken",
    "commonall_enterfield_title_wallet": "Portemonnee",
    "nav_desc_premkt_trade_upcoming_crypto": "Krijg vroege toegang en handel in aankomende crypto",
    "commonall_modal_title_fee": "Vergoeding",
    "commonall_column_colheader_assets": "Activa",
    "navdropdown_header_textarea_master_crypto": "Krijg belangrijke basisprincipes van crypto onder de knie met eenvoudige handleidingen en tutorials",
    "commonall_filter_btn_delete": "Verwijderen",
    "commonall_enterfield_title_last_price": "Laatste prijs",
    "commonall_text_label_tab_trading_account": "Handelsaccount",
    "nav_dropdown_spot_copy_trading": "Spot copy trading",
    "nav_web3_header_nav_option_test_faucet": "Testnet-kraan",
    "commonall_enterfield_title_buy": "Kopen",
    "nav_assets_dropdown_report": "Ordercentrum",
    "nav_nav_campaign_center": "Campagnecentrum",
    "commonall_button_text_send": "Versturen",
    "nav_dex_dropdown_tooltip_token_name": "Vertaal namen van tokens automatisch naar Chinees of Engels",
    "commonall_enterfield_text_amount_ccy": "Bedrag",
    "nav_okxalert_dns_title_tips": "Herinnering",
    "nav_country_pop_up_content_br": "Acesse o site do Brasil para ver os produtos disponíveis na sua região.",
    "commonall_colheader_text_action": "Handeling",
    "commonall_text_payment_method": "Betalingsmethode",
    "nav_dropdown_smart_trading": "Marktplaats",
    "commonall_enterfield_title_crypto": "Crypto",
    "commonall_emptystate_text_page_404_title": "Deze pagina kan niet worden uitgehasht",
    "tr_nav_header_dropdown_desc_add_try_to_account": "Voeg direct TRY toe aan je OKX TR-accountsaldo via bankoverschrijving",
    "nav_finance_dropdowntitle_btcyield": "BTC Yield+",
    "commonall_modal_title_type": "Type",
    "nav_compliance_variable_complete_id": "Voltooi je identiteitsverificatie",
    "commonall_button_text_done": "Klaar",
    "nav_restrictedproduct_error_bodypostlogin": "Dit product is niet verkrijgbaar in {country} vanwege lokale wetten en regels. Maar er is meer te ontdekken op onze homepage.",
    "nav_dex_clipboard_introduction_popup_header": "Instellingen klembord",
    "nav_menu_btn_download": "OKX-app downloaden",
    "nav_setting_text2_local_currency": "Lokale valuta",
    "commonall_tab_text_nft": "NFT",
    "nav_okalert_footer_ip_checkbox_cancel": "Niet weergeven voor 7 dagen",
    "nav_assets_dropdown_trading_fee": "Mijn handelskosten",
    "nav_uk_risk_warning_header_title_warning": "Risicowaarschuwing",
    "tr_nav_header_dropdown_title_try": "TRY",
    "navdropdown_header_title_how_to_buy_crypto": "Zo koop je crypto",
    "commonall_enterfield_btn_max": "Max",
    "commonall_tag_text_new": "Nieuw",
    "nav_dex_clipboard_popup_cta_later": "Sluiten",
    "nav_rbac_tooltip_changing_currency": "Het wijzigen van de valuta heeft invloed op de instellingen van deze subrekening voor alle gebruikers",
    "commonall_text_btn_tab_buy": "Koop",
    "nav_tr_btn2_confirm": "Bevestigen",
    "tr_nav_footer_text_copyright": "©TR.OKX.COM",
    "nav_account_btn_vip_group": "Je VIP-groep",
    "nav_boost_title_xcampaign": "X-campagne",
    "commonall_tab_tag_dropdown_spot": "Spot",
    "nav_home_header_chat": "Chat",
    "nav_title_web3_eea_restricted": "OKX Web3-softwarediensten zijn momenteel niet beschikbaar in de EER-regio.",
    "commonall_text_btn_view": "Bekijken",
    "nav_dex_header_leaderboard": "Scorebord",
    "nav_finance_dropdowntitle_simple_earn": "Simple Earn",
    "nav_desc_set_up_risk_units": "Je risico-eenheden instellen en beheren",
    "nav_mktcon_btn2_no_thanks": "Nee, bedankt",
    "commonall_text_btn_view_more": "Meer bekijken",
    "nav_wallet_general_link_terms_service": "Servicevoorwaarden",
    "nav_web_homepage_footer_nmls": "NMLS #1767779",
    "nav_nft_market_mid_modaldesc_region_unavailable_all": "OKX Web3 marktplaats-producten zijn niet beschikbaar in {country}. Je hebt nog steeds toegang tot andere functies van OKX DEX.",
    "nav_logo_text_desc": "OKX: De marktleidende beurs voor cryptocurrency's",
    "commonall_resultpage_btn_delete": "Verwijderen",
    "commonall_modal_title_reminder": "Herinnering",
    "nav_nav_institutions_title_manage_subacct": "Subaccounts voor degelegeerde handel",
    "nav_wallet_header_nav_title_earn": "DeFi",
    "commonall_modal_title_price": "Prijs",
    "commonall_label_colheader_tab_mark_price": "Markeerprijs",
    "nav_explorer_main_header_emptystate_network_error": "Netwerkfout, probeer het later opnieuw.",
    "commonall_enterfield_btn_submit": "Indienen",
    "nav_buy_crypto_subtitle_p2p": "Kopen/verkopen zonder handelskosten met meer dan 100+ betaalmethoden",
    "commonall_resultpage_btn_add": "Toevoegen",
    "nav_desc_market_maker_portal": "De prestaties van je marktmakersprogramma in de gaten houden",
    "nav_trade_header_dex": "DEX",
    "nav_menu_btn_demo_api": "API voor demohandel",
    "commonall_button_text_previous": "Vorige",
    "nav_dex_bar_swap": "Swap",
    "nav_web3_header_nav_option_tutorial": "Tutorial",
    "nav_dex_header_more": "Meer",
    "nav_more_dropdown_por": "Bewijs van reserves",
    "nav_more_dropdowntitle_listing_application": "Toepassing voor notering",
    "nav_assets_dropdowntitle_audit": "Rapporten over bewijs van reserves",
    "nav_assets_dropdown_withdraw": "Opnemen",
    "nav_nav_more": "Meer",
    "commonall_column_tab_fees": "Vergoedingen",
    "nav_msg_homepage_nav_okx_protect": "OKX Protect",
    "commonall_column_tab_addresses": "Adressen",
    "nav_pc_client_upgrade_download_btn": "Download de OKX-app",
    "commonall_enterfield_btn_trade": "Handelen",
    "commonall_resultpage_toast_copied": "Gekopieerd",
    "commonall_column_tab_options": "Opties",
    "commonall_label_title_date_of_birth": "Geboortedatum",
    "commonall_enterfield_btn_copy_link": "Link kopiëren",
    "commonall_modal_btn_trade": "Handelen",
    "nav_compliance_text_complete_make_cash": "{completeIdentityVerification} opnieuw om geld te storten en op te nemen van je account.",
    "nav_trade_nitro_spreads_desc": "Diepe liquiditeit voor futures-spreads",
    "nav_okxalert_dns_title_client": "Gebruik OKX-client",
    "nav_web3_header_nav_option_all_about_web3": "Alles over Web3",
    "commonall_filter_btn_save": "Opslaan",
    "nav_signup_btn_signup": "Aanmelden",
    "nav_language_title_uae": "VAE",
    "commonall_filter_dropdown_earn": "Earn",
    "nav_home_footerdesc_not_available_ontario": "De producten van OKX Exchange zijn niet beschikbaar in {0} vanwege lokale wetten en regels.",
    "nav_country_pop_up_content": "Schakel over naar de {country} site voor producten die in jouw regio verkrijgbaar zijn.",
    "commonall_button_text_next": "Volgende",
    "commonall_colheader_label_remarks": "Opmerkingen",
    "nav_nav_institutions_dropdowntitle_broker": "Brokerprogramma",
    "nav_investhome_mid_modal_ok": "OK",
    "commonall_enterfield_title_instrument": "Instrument",
    "commonall_text_btn_edit": "Bewerken",
    "commonall_text_colheader_description": "Beschrijving",
    "nav_xlayer_mid_modaldesc_region_unavailable_all": "Vanwege lokale wet- en regelgeving is dit X Layer-product niet beschikbaar in {country}. Je hebt nog steeds toegang tot andere functies van X Layer.",
    "nav_dex_clipboard_introduction_popup_description": "Detecteer automatisch een contractadres dat is gekopieerd naar je klembord en toon het token bovenaan de pagina in de quickview.",
    "nav_investhome_mid_modaldesc_region_unavailable": "Vanwege lokale wet- en regelgeving is dit Web3-product van OKX niet beschikbaar in {0}. Je hebt nog steeds toegang tot andere functies van OKX DEX.",
    "commonall_enterfield_title_price": "Prijs",
    "commonall_column_colheader_funding_account": "Financieringsrekening",
    "nav_invest_mid_modaldesc_region_unavailable": "Earn-producten zijn niet beschikbaar in {country}. Je hebt nog steeds toegang tot andere functies van OKX DEX.",
    "nav_nav_usermenu_alt": "Gebruikersmenu",
    "commonall_datetime_abbr_month": "M",
    "nav_dialog_checkbox_do_not_show_again_7": "7 dagen lang niet opnieuw tonen",
    "nav_dex_clipboard_popup_ok_cta_button": "OK",
    "commonall_modal_title_account": "Rekening",
    "nav_trade_request_for_quote": "Offerteaanvraag (Request for Quote)",
    "nav_view_home_navi_nft": "Marktplaats",
    "nav_avatar_dropdowntitle_overview": "Overzicht",
    "nav_explorer_main_header_dropdown_input_search_chain": "Netwerk zoeken",
    "nav_boost_title_launchpool": "X Launch",
    "nav_nav_institutions_desc_api": "Naadloze API-connectiviteit met ultralage latency",
    "nav_dex_dropdown_item_auto_hover_to_show_token_card": "Tokenkaart tonen als je er over beweegt",
    "nav_okx_directory_alt": "Adresboek van OKX",
    "nav_language_title_united_kingdom": "Verenigd Koninkrijk",
    "nav_skip_to_main_content_alt": "Overslaan naar hoofdinhoud",
    "nav_finance_dropdowntitle_jumpstart": "Jumpstart",
    "nav_okxalert_dns_title_desc": "Lokale netwerk-DNS wijzigen",
    "commonall_modal_title_network": "Netwerk",
    "commonall_tab_btn_swap": "Swap",
    "nav_exp_footer_text_copyright": "©2017 - {0} OKX.COM",
    "nav_bottom_toast_btn_goto_okxwallet3": "Ga naar OKX Wallet",
    "commonall_text_btn_tab_sell": "Verkoop",
    "nav_offshore_banner_argentina_btn": "Go to the global site",
    "trade_optionsmarket_cell_tag_advanced_options": "Geavanceerde opties",
    "nav_nav_institutions": "Institutioneel",
    "nav_okx_web_home_au_wholesale_entry_new": "Wholesale",
    "commonall_timeformat_title_to": "Naar",
    "nav_bottom_toast_title_okx_not_available": "De producten van OKX Exchange zijn niet beschikbaar in jouw regio",
    "commonall_label_text_est_apr": "Gesch. APR",
    "commonall_modal_btn_settings": "Instellingen",
    "nav_nav_trade_tools_title_copy_trading": "Copy trading",
    "commonall_resultpage_title_processing": "Bezig met verwerken",
    "commonall_filter_title_market_cap": "Marktlimiet",
    "nav_web3_settings_option_language": "Taal",
    "nav_restrictedproduct_btn_login": "Inloggen",
    "commonall_modal_btn_deposit": "Storten",
    "commonall_resultpage_btn_more": "Meer",
    "nav_cex_header_depositfiat_new": "Geld storten",
    "nav_dropdown_lead_trader_recruitment": "Lead trader-werving",
    "navdropdown_header_title_crypto_calculator": "Cryptocalculator",
    "nav_avatar_dropdown_verfication": "Verificatie",
    "commonall_modal_title_rewards": "Beloningen",
    "nav_nav_download_app": "App downloaden",
    "nav_dex_header_signal": "Signaal",
    "commonall_text_btn_cancel": "Annuleren",
    "navdropdown_header_textarea_check_conversion_rates": "Check realtime wisselkoersen en cryptowaarden",
    "commonall_emptystate_text_no_internet": "Geen internetverbinding",
    "trade_optionsmarket_cell_tag_simple_options_two": "Eenvoudige opties",
    "nav_explorer_main_header_emptystate_no_results": "Geen resultaten beschikbaar",
    "nav_pc_client_download_tips": "Er is een nieuwe versie beschikbaar.",
    "tr_nav_footer_text_full_name": "Volledige naam van het bedrijf: OKX TR Kripto Varlık Alım Satım Platformu Anonim Şirketi",
    "nav_web3_header_nav_btn_google_play": "Google Play",
    "nav_dialog_header_gotowallet": "Je wordt doorgestuurd naar OKX Wallet",
    "commonall_modal_btn_continue": "Doorgaan",
    "commonall_modal_btn_buy_crypto": "Crypto kopen",
    "commonall_resultpage_btn_download": "Downloaden",
    "nav_web3_header_nav_option_dapp_connect": "Koppel je wallet met DApps",
    "commonall_filter_title_type": "Type",
    "nav_new_tag_text": "Nieuw",
    "nav_desc_trading_digital_crypto_perp": "Verhandel perpetual en tijdelijke futures met hefboomwerking",
    "nav_web3_header_settings_dialog_item_green_up_red_down": "Groen omhoog, rood omlaag",
    "nav_trade_options": "Opties",
    "nav_avatar_dropdown_subaccount": "Subaccounts",
    "nav_nav_hamburgermenu_alt": "Menu met extra opties openen",
    "commonall_button_text_share": "Delen",
    "commonall_emptystate_text_page_500_subtitle": "Als er niet snel een consensus wordt bereikt, vernieuw je de pagina of neem je contact op via {support}.",
    "nav_boost_title_giveaway": "Giveaway",
    "commonall_filter_btn_apply": "Toepassen",
    "commonall_column_tab_network_fee": "Netwerkvergoeding",
    "nav_wallet_terms_hyperlink_faq_page": "Pagina met veelgestelde vragen",
    "nav_web3_header_settings_desc_color_modern": "Modern",
    "nav_trade_title_spot": "Spot",
    "nav_dropdown_live_trading": "Live handel",
    "nav_notice_dropdown_more": "Meer aankondigingen",
    "nav_assets_dropdown_custody": "Assets in bewaring",
    "nav_boost_title_dex_competition": "Handelswedstrijd",
    "nav_nav_trade_tools_desc_copy_trading": "Spiegel de beslissingen van toptraders",
    "nav_language_title_singapore": "Singapore",
    "nav_tospopup_btn_confirm": "Bevestigen",
    "nav_dex_clipboard_browser_settings_link_copied_toast": "Link gekopieerd. Plak dit in een nieuw tabblad om de instellingen te openen.",
    "commonall_colheader_title_symbol": "Symbool",
    "nav_web3_header_okc_btn_wallet": "Wallet koppelen",
    "commonall_resultpage_title_status": "Status",
    "nav_nav_globe_alt": "Taal of valuta wijzigen",
    "tr_nav_header_nav_deposit": "Storten",
    "nav_web3_settings_option_theme": "Thema",
    "commonall_text_tag_yes": "Ja",
    "nav_dropdown_language_currency_alt": "Geselecteerde taal en valuta: {lang}/{currency}",
    "commonall_enterfield_title_token": "Token",
    "nav_boost_desc_launchpool": "Doe mee en verdien tokens",
    "commonall_text_link_terms_of_service": "Servicevoorwaarden",
    "commonall_text_contract_address": "Contractadres",
    "commonall_colheader_text_actions": "Handelingen",
    "commonall_text_colheader_or": "of",
    "nav_dex_header_market": "Markt",
    "commonall_toast_text_copied": "Gekopieerd",
    "nav_swaptrade_mid_modaldesc_region_unavailable": "OKX DEX-producten zijn niet beschikbaar in {country}. Je hebt nog steeds toegang tot andere functies van OKX Web3.",
    "commonall_btn_tab_text_mint": "Minten",
    "tr_nav_header_nav_withdraw": "Opnemen",
    "nav_dex_dropdown_clipboard_status_enabled": "Ingeschakeld",
    "nav_more_dropdowntitle_referral": "Verwijzing",
    "nav_boost_desc_giveaway": "Voltooi taken om airdrops te ontvangen",
    "tr_nav_language_reminder_your_lang_selection": "Je taalkeuze is van toepassing op OKX Türkiye-e-mails, in-app meldingen en alle apparaten waarop je bent ingelogd",
    "nav_nav_institutions_dropdowntitle_block": "Liquid Marketplace",
    "commonall_filter_btn_add": "Toevoegen",
    "commonall_btn_text_reject": "Verwerpen",
    "nav_finance_dropdowntitle_structure_products": "Dual Investment",
    "nav_downloadpage_landing_popover_troubleshoot_email": "Heb je een probleem? Stuur ons een e-mail op download@okx.com om een downloadlink te ontvangen.",
    "nav_cex_desc_depositcrypto": "Crypto overschrijven van een on-chain-wallet of beurs",
    "nav_btn_trade": "Handelen",
    "commonall_title_tab_language": "Taal",
    "nav_account_user_id": "UID: {0}",
    "commonall_text_btn_ok_active": "OK",
    "commonall_modal_btn_withdraw": "Opnemen",
    "nav_kyc_top_textbtn_guidance": "Eenvoudig crypto kopen en verkopen",
    "commonall_text_btn_back": "Terug",
    "commonall_button_add_to_favorites": "Toevoegen aan favorieten",
    "commonall_filter_btn_download": "Downloaden",
    "nav_popup_btn_ok": "OK",
    "nav_avatar_dropdown_api": "API",
    "commonall_filter_dropdown_perpetual": "Eeuwigdurend",
    "commonall_filter_dropdown_spot": "Spot",
    "navdropdown_header_textarea_track_prices": "Volg realtime cryptoprijzen en marktbewegingen",
    "nav_web3_header_nav_textbtn_back": "Teruggaan",
    "commonall_modal_btn_apply": "Toepassen",
    "nav_web3_header_nav_btn_extension": "Extensie",
    "nav_dex_dropdown_security": "Bewaking",
    "commonall_filter_title_name": "Naam",
    "nav_home_popup_access_restricted_describe": "Producten of diensten van okx.com zijn niet beschikbaar in jouw regio ({area}) volgens de lokale wetten en regelgeving.",
    "nav_banner_dialog_title_country_content_us": "Het lijkt erop dat je in de {country} bent",
    "commonall_button_text_start": "Beginnen",
    "nav_web3_header_settings_dialog_item_red_up_green_down": "Rood omhoog, groen omlaag",
    "nav_signup_btn_login": "Inloggen",
    "nav_dropdowntitle_assets": "Bezittingen",
    "nav_okxalert_dns_btn_cancel": "Herinner niet binnen 7 dagen",
    "nav_caas_hero_okx_rubrix": "OKX Rubix",
    "commonall_datetime_abbr_minute": "m",
    "nav_web3_header_settings_dialog_title_chart_colors": "Grafiekkleuren",
    "nav_nav_institutions_desc_boker": "Toegang tot marktdiepte van wereldklasse met hoge commissies",
    "commonall_button_text_view_all": "Alles bekijken",
    "nav_dex_dropdown_tooltip_hover_token_show_card": "Beweeg met je muis over het pictogram of de naam van een token om gerelateerde informatie te zien",
    "nav_dropdown_download_more_options": "Meer opties",
    "nav_avatar_tag_subaccount": "Subaccount",
    "nav_web3_settings_option_currency": "Valuta",
    "tr_nav_footer_text_mersis": "MERSIS No.:0638068598100001",
    "commonall_datetime_abbr_year": "Y",
    "nav_colbody1_cookie_preference": "Cookievoorkeuren",
    "commonall_filter_btn_transfer": "Overschrijven",
    "commonall_resultpage_title_details": "Details",
    "nav_trade_desc_dex": "Handel in on-chain tokens met je Exchange-saldo\u00a0",
    "nav_compliance_text_verify_resume": "{verifyYourIdentity} om weer geld te storten en crypto te verhandelen.",
    "commonall_column_tab_all": "Alle",
    "nav_more_dropdowntitle_status": "Status",
    "nav_bottom_toast_okx_not_available_describe": "OKX Exchange is momenteel niet beschikbaar in {country} door lokale wetten en regelgeving. Als je niet woonachtig bent in {country}, kun je OKX Exchange blijven gebruiken met een officieel identiteitsbewijs dat door de overheid is verstrekt.",
    "nav_discover_mid_modaldesc_region_unavailable_all": "OKX Web3 Discover-producten zijn niet beschikbaar in {country}. Je hebt nog steeds toegang tot andere functies van OKX DEX.",
    "nav_compliance_text_verify_by_date": "Om aan de lokale wetgeving te voldoen, moet je nogmaals {verifyYourIdentity} voor {date}, anders wordt je account geblokkeerd.",
    "commonall_filter_btn_edit": "Bewerken",
    "navdropdown_header_title_crypto_prices": "Cryptoprijzen",
    "commonall_colheader_text_from": "Van",
    "nav_title_institutions_insights": "Institutionele inzichten",
    "commonall_filter_dropdown_select": "Selecteren",
    "nav_search_input_pair_trader": "Crypto of producten zoeken",
    "navdropdown_header_title_learn_crypto": "Leer crypto",
    "navdropdown_header_title_fees": "Kosten",
    "nav_account_dropdown_profile": "Profiel",
    "nav_nav_account_label_regular_user": "Vaste gebruiker",
    "navdropdown_header_textarea_latest_trends": "Blijf op de hoogte van het laatste cryptonieuws en de nieuwste trends",
    "commonall_column_tab_receive": "Ontvangen",
    "nav_boost_desc_rewards_center": "Claim bonussen en airdrops",
    "nav_exp_footer_text_copyright_web3": "©2017 - {year} WEB3.OKX.COM",
    "commonall_filter_btn_reset": "Opnieuw instellen",
    "nav_header_trade_dropdown_subtitle_margin_unlock_now": "Krijg nu toegang tot een volledig assortiment contracten en margeproducten",
    "commonall_text_btn_ok_passive": "OK",
    "nav_market_top_alerts": "Waarschuwing",
    "tr_nav_footer_text_registered_address": "Geregistreerd adres: Maslak Mah., AOS 55. Sk. 42 Maslak B Blok Sitesi No: 4 İç Kapı No: 542, Sarıyer/Istanbul, Turkije",
    "commonall_modal_btn_log_in": "Inloggen",
    "commonall_enterfield_text_quantity": "Aantal",
    "nav_search_input_pair_finance_bots_trader_seo_tdk": "Crypto zoeken",
    "nav_rbac_dropdown_item_team_account": "Teamleden",
    "nav_popup_text_web3_wallet_singapore": "Je opent nu de Web3-wallet die wordt beheerd door OKX Technology Inc., een dienstverlener op het gebied van software voor non-custodial wallets. Op alle diensten zijn de servicevoorwaarden van het OKX Web3-ecosysteem van toepassing.",
    "commonall_datetime_abbr_week": "W",
    "navdropdown_header_textarea_common_questions": "Vind antwoorden op veelgestelde vragen tijdens je cryptoreis",
    "nav_dex_clipboard_introduction_popup_guide_to_enable_later": "Om deze functie later te gebruiken, moet je toegang tot het klembord inschakelen in je {browser}.",
    "nav_menu_btn_submenu": "Submenu {title} openen",
    "nav_nav_my_rewards": "Mijn beloningen",
    "nav_trade_spot": "Spot",
    "nav_avatar_dropdown_vip_support": "VIP-ondersteuning",
    "nav_uk_risk_warning_header_subtitle_warning": "<div class=\"content-info\"><div class=\"headings-1\">Geschatte leestijd: 2 min</div><div class=\"headings-desc\">Vanwege de kans op verliezen beschouwt de Financial Conduct Authority (FCA) deze investering als zeer risicovol.</div><div class=\"headings-2\">Wat zijn de belangrijkste risico's?</div><div class=\"sub-title\"><span class=\"sub-order\">1.</span>Je kunt al je geïnvesteerde geld verliezen</div><div class=\"sub-desc\"><div class=\"desc\" style=\"\n    width: 100%;\n    padding-left: 24px;\n    box-sizing: border-box;\n\"><span class=\"dot\"></span>De prestaties van de meeste cryptoactiva kunnen zeer volatiel zijn, waarbij hun waarde net zo snel kan dalen als stijgen. Je moet bereid zijn om al het geld dat je in cryptoactiva investeert te verliezen.</div><div class=\"desc\"><span class=\"dot\"></span>De cryptoactivamarkt is grotendeels ongereguleerd. Er is een risico dat je geld of cryptoactiva die je koopt verliest door risico's zoals cyberaanvallen, financiële criminaliteit en faillissementen.</div></div><div class=\"sub-title\"><span class=\"sub-order\">2.</span>Je moet niet verwachten dat je beschermd wordt als er iets misgaat</div><div class=\"sub-desc\"><div class=\"desc\"><span class=\"dot\"></span><p>Het Financial Services Compensation Scheme (FSCS) beschermt dit type investering niet omdat het geen 'gespecificeerde investering' is onder de Britse regelgeving. Met andere woorden, dit type investering wordt niet erkend als het soort investering dat het FSCS kan beschermen. Lees hier meer over de FSCS investeringsbescherming checker.<a class=\"other-link\" href=\"https://www.fscs.org.uk/check/investment-protection-checker/\" target=\"_blank\" rel=\"noreferrer\">https://www.fscs.org.uk/check/investment-protection-checker</a></p></div><div class=\"desc\"><span class=\"dot\"></span><p>De Financial Ombudsman Service (FOS) kan geen klachten met betrekking tot dit bedrijf in behandeling nemen. Lees hier meer over de bescherming van de FOS.<a class=\"other-link\" href=\"https://www.financial-ombudsman.org.uk/consumers\" target=\"_blank\" rel=\"noreferrer\">https://www.financial-ombudsman.org.uk/consumers</a></p></div></div><div class=\"sub-title\"><span class=\"sub-order\">3.</span>. Je kunt je investering misschien niet verkopen wanneer je wilt</div><div class=\"sub-desc\"><div class=\"desc\"><span class=\"dot\"></span>Er is geen garantie dat investeringen in cryptoactiva op een bepaald moment gemakkelijk verkocht kunnen worden. De mogelijkheid om een cryptoactiva te verkopen hangt af van verschillende factoren, waaronder de vraag en het aanbod op de markt op dat moment.</div><div class=\"desc\"><span class=\"dot\"></span>Operationele storingen zoals technologische uitval, cyberaanvallen en vermenging van fondsen kunnen ongewenste vertraging veroorzaken en het kan zijn dat je je cryptoactiva niet kunt verkopen op het moment dat je wilt.</div></div><div class=\"sub-title\"><span class=\"sub-order\">4.</span>Investeren in cryptoactiva kan complex zijn</div><div class=\"sub-desc\"><div class=\"desc\"><span class=\"dot\"></span>Investeringen in cryptoactiva kunnen complex zijn, waardoor het moeilijk is om de risico's van de investering te begrijpen.</div><div class=\"desc\"><span class=\"dot\"></span>Je moet je eigen onderzoek doen voordat je investeert. Als iets te mooi klinkt om waar te zijn, is dat waarschijnlijk ook zo.</div></div><div class=\"sub-title\"><span class=\"sub-order\">5.</span>Leg niet al je eieren in één mandje</div><div class=\"sub-desc\"><div class=\"desc\"><span class=\"dot\"></span>Al je geld in één soort investering stoppen is riskant. Door je geld te spreiden over verschillende investeringen ben je minder afhankelijk van één investering om het goed te doen.</div><div class=\"desc\"><span class=\"dot\"></span>Een goede vuistregel is om niet meer dan 10% van je geld te investeren in risicovolle investeringen.</div></div><div class=\"other-desc\">Als je meer wilt weten over hoe je jezelf kunt beschermen, bezoek dan hier de website van de FCA.</div><a class=\"other-link\" href=\"https://www.fca.org.uk/investsmart\" target=\"_blank\" rel=\"noreferrer\">https://www.fca.org.uk/investsmart</a><div class=\"other-desc\">Ga voor meer informatie over cryptoactiva hier naar de website van de FCA.</div><a class=\"other-link\" href=\"https://www.fca.org.uk/investsmart/crypto-basics\" target=\"_blank\" rel=\"noreferrer\">https://www.fca.org.uk/investsmart/crypto-basics</a></div>",
    "nav_restrictedproduct_btn_homepage": "Naar de startpagina gaan",
    "nav_caas_hero_subheader": "Digitale bezittingen als dienst voor gereguleerde instellingen",
    "commonall_filter_btn_select_all": "Alles selecteren",
    "nav_nav_build": "Bouwen",
    "nav_dex_clipboard_click_to_enable_tooltip": "Klik hier om toegang tot het klembord in te schakelen",
    "nav_language_alert_back_to_language": "Ga terug naar de {globalVersion}.",
    "nav_buy_crypto_subtitle_desc": "Visa, Mastercard en andere",
    "nav_nav_institutions_dropdowntitle_data": "Historische marktgegevens",
    "nav_dropdown_demo_trading_desc": "Leer crypto beleggen en oefen zonder risico",
    "nav_qrcode_scan_to_download": "Scan om de OKX-app te downloaden",
    "commonall_enterfield_btn_transfer": "Overschrijven",
    "commonall_filter_btn_apply_search": "Toepassen",
    "nav_web3_header_nav_label_scan_download_okx": "Scan om de OKX-app te downloaden",
    "commonall_enterfield_title_balance": "Saldo",
    "nav_assets_dropdown_analysis": "Analyse",
    "nav_cex_header_depositcrypto": "Crypto storten",
    "nav_dex_clipboard_introduction_hyperlink_text_broswer_settings": "browserinstellingen",
    "commonall_column_colheader_operation": "Bewerking",
    "nav_dialog_btn_back": "Terug",
    "commonall_column_tab_pool": "Pool",
    "commonall_modal_btn_transfer": "Overschrijven",
    "nav_arbitrage_order_comb_trade_header_totalempty_amount": "Meerdere strategieën om gemakkelijk te handelen",
    "nav_dex_dropdown_okx_dex_features": "DEX-functies",
    "nav_rbac_tag_team_account": "Teamaccount",
    "commonall_text_title_share_telegram": "Telegram",
    "navdropdown_header_title_trendy_news": "Cryptonieuws",
    "commonall_datetime_abbr_day": "D",
    "nav_web3_search_placeholder_name_address": "Token, adres of DApp zoeken",
    "nav_dex_dropdown_item_clipboard": "Klembord detecteren",
    "commonall_enterfield_text_buy": "Stad",
    "commonall_placeholder_text_please_select": "Maak een selectie",
    "nav_web3_header_nav_option_support_center": "Ondersteuningscentrum",
    "nav_dex_dropdown_item_auto_translate_token_name": "Naam van token vertalen",
    "nav_assets_dropdown_deposit": "Storten",
    "nav_discover_dropdowntitle_opportunities": "Kansen",
    "nav_avatar_dropdown_authenization": "Toestemming van derden",
    "nav_defi_spot_mid_modaldesc_region_unavailable_all": "OKX Web3 Spot-producten zijn niet beschikbaar in {country}. Je hebt nog steeds toegang tot andere functies van OKX Wallet.",
    "nav_web3_header_nav_option_github": "GitHub",
    "commonall_filter_dropdown_futures": "Aflopend",
    "nav_web3_settings_option_download_wallet": "Download OKX Wallet",
    "nav_avatar_dropdown_security_setting": "Beveiliging",
    "nav_web3_header_nav_option_bridge": "Brug",
    "nav_offshore_banner_argentina_title": "This website is currently unavailable",
    "nav_web3_header_nav_option_manage_api": "API-sleutels beheren",
    "commonall_modal_title_total": "Totaal",
    "commonall_text_tag_no": "Nee",
    "nav_finance_dropdowntitle_onchain_earn": "On-chain Earn",
    "tr_nav_header_dropdown_title_crypto": "Crypto",
    "nav_more_dropdowntitle_affiliates": "Partners",
    "tr_nav_footer_qrcode_scan_to_download": "Scan en download de OKX TR-app",
    "nav_dex_dropdown_clipboard_status_enable_now": "Inschakelen",
    "nav_language_title_australia": "Australië",
    "nav_offshore_banner_argentina_desc": "This platform isn't available in Argentina. For more information about OKX Global, click the button below.",
    "nav_okxalert_dns_btn_download": "Nu downloaden",
    "nav_brand_name": "OKX",
    "nav_dropdown_demo_trading": "Demohandel",
    "nav_language_title_europe": "Europa",
    "nav_banner_dialog_title_country_content": "Het lijkt erop dat je in {country} bent",
    "nav_okxalert_dns_link_change_guide": "Hoe instellen",
    "nav_discoverhome_navbar_title_dropzone_insighthub": "Inzichtenhub",
    "nav_dex_clipboard_introduction_popup_how_to_disable_later": "Om deze functie niet langer te gebruiken, schakel je toegang tot het klembord uit in je {browser}.",
    "nav_discover_subtitle_view": "Bekijk de meest recente koersen, volumes en gegevens van crypto's",
    "nav_nav_learn": "Learn",
    "tr_nav_footer_slogan_trade_on_the_go": "Handel onderweg met OKX TR",
    "commonall_tab_dropdown_margin": "Marge",
    "nav_wallet_header_nav_title_browser": "Blockchain verkenner",
    "commonall_emptystate_text_page_500_variate": "support@okx.com",
    "nav_xdrops_title_xdropsclub": "X Drops Club",
    "commonall_resultpage_btn_close": "Sluiten",
    "nav_okx_web_home_au_smsf_entry_new": "SMSF",
    "commonall_resultpage_tag_canceled": "Voltooid",
    "nav_okalert_footer_ip_btn_verification": "Identiteit verifiëren",
    "nav_xlayer_mid_modaltitle_region_unavailable": "Dit X Layer-product is niet beschikbaar in jouw regio",
    "nav_hk_bottom_toast_okx_not_available_describe": "OKX Exchange is momenteel niet beschikbaar in Hong Kong SAR (China) vanwege lokale wet- en regelgeving. OKX heeft {textLink} dat het vanaf mei 2024 geen diensten voor het verhandelen van digitale bezittingen meer aanbiedt in Hongkong.\n\nAls je niet woonachtig bent in Hong Kong SAR (China), kun je OKX Exchange gebruiken met een geldig officieel identiteitsbewijs.",
    "commonall_enterfield_title_from": "Van",
    "commonall_filter_dropdown_others": "Overigen",
    "nav_more_dropdowntitle_security_of_funds": "Veiligheid van vermogen",
    "nav_notice_dropdown_text_desc": "Geen aankondiging",
    "nav_avatar_dropdown_logout": "Uitloggen",
    "commonall_status_tab_tag_ended": "Afgelopen",
    "commonall_filter_title_free": "Gratis",
    "commonall_column_tab_order_id": "Order-ID",
    "nav_nav_download_alt": "Download onze app. Het keuzemenu bevat een QR-code en andere downloadopties.",
    "nav_web3_settings_option_notifications": "Aankondigingen",
    "nav_title_trading_instruments": "Handelsinstrumenten",
    "home_nav_finance_dropdowntitle_flash_earn": "Flash-Earn",
    "commonall_enterfield_toast_copied": "Gekopieerd",
    "nav_wallet_terms_body_update_notice": "Het OKX Web3-ecosysteem {tos} is geüpdatet. Door OKX Wallet te blijven gebruiken, ga je akkoord met de geüpdatete voorwaarden.\n\nVoor meer informatie kun je onze {faq} bezoeken.",
    "nav_web3_header_nav_option_explore_dexapi": "Ontdek de Wallet API",
    "tr_nav_header_dropdown_desc_receive_crypto_from_others": "Ontvang crypto van wallets of accounts op andere platforms",
    "commonall_title_placeholder_select_network": "Netwerk selecteren",
    "commonall_filter_title_volume": "Volume",
    "nav_nav_card_express_buy_crypto": "Kopen en verkopen",
    "commonall_modal_btn_copy": "Kopiëren",
    "tr_nav_header_nav_support": "Ondersteuning",
    "nav_discover_subtitle_discover_and_stay": "Ontdek populaire en nieuwe crypto's",
    "commonall_enterfield_title_user_id": "Gebruikers-ID",
    "nav_thirddetailchannel3_header2_title_confirm": "Snelle conversie, geen handelskosten, geen prijsverschuiving",
    "nav_nav_okxlogo_alt": "OKX-logo, ga naar de startpagina",
    "commonall_emptystate_text_page_500_title": "Er ging iets buiten de chain",
    "nav_buy_crypto_btn_c2c": "P2P-handelen",
    "commonall_modal_btn_done": "Klaar",
    "nav_homepage_nav_web3": "Web3",
    "commonall_colheader_text_unit_price": "Eenheidsprijs",
    "nav_entry_xbtc": "xAssets",
    "nav_dropdown_futures_copy_trading": "Copy trading in futures",
    "commonall_timeformat_title_date": "Datum",
    "nav_finance_dropdowntitle_earn": "Earn",
    "commonall_modal_btn_i_understand": "Ik begrijp het",
    "nav_assets_dropdown_demo_trading": "Demohandel",
    "commonall_timeformat_title_from": "Van",
    "nav_web3_header_nav_option_xlayer_exp": "X Layer Explorer",
    "nav_web3_header_nav_option_explore_xlayer": "Meer informatie over X Layer",
    "commonall_btn_title_modify": "Bewerken",
    "nav_assets_dropdown_my_assets": "Mijn portfolio",
    "nav_nav_boost": "Boost",
    "nav_dropdowntitle_support_center": "Ondersteuningscentrum",
    "nav_dropdowntitle_connect_with_okx": "Contact met OKX",
    "commonall_text_label_share_x": "X",
    "nav_okxalert_app_title_okx_app": "OKX APP",
    "commonall_label_title_term": "Termijn",
    "commonall_btn_text_show_less": "Minder weergeven",
    "nav_boost_desc_dex_competition": "Verhandel populaire tokens om prijzen te winnen",
    "nav_dex_clipboard_introduction_popup_second_description": "Klik op ‘Toestaan’ als je daarom wordt gevraagd, of schakel handmatig toegang tot het klembord in je {browser} in.",
    "nav_country_banner_content": "Het lijkt erop dat je in {country} bent. Schakel over naar de {country} site voor producten die in jouw regio beschikbaar zijn.",
    "commonall_text_btn_learn_more": "Meer informatie",
    "nav_nav_buy_crypto": "Crypto kopen",
    "nav_okxalert_app_subtitle_desc": "Altijd en overal handelen",
    "nav_wallet_terms_title_updated": "We hebben onze Servicevoorwaarden geüpdatet",
    "nav_dropzone_risk_unit_portal": "Portaal voor risico-eenheid",
    "nav_cex_top_depositcrypto": "Storten",
    "nav_nav_institutions_desc_manage_subacct": "Beheer subaccounts, handel eenvoudig en veilig met meer winst",
    "nav_explorer_main_header_dropdown_link_all_chains": "Alle {num}netwerken",
    "commonall_btn_text_verify": "Verifiëren",
    "nav_bottom_community": "Community",
    "nav_wallet_general_checkbox_understand": "Begrepen",
    "commonall_resultpage_tag_expired": "Vervallen",
    "nav_home_popup_title_access_restricted": "Toegang beperkt",
    "commonall_modal_text_insufficient_balance": "Onvoldoende saldo",
    "commonall_enterfield_title_sell": "Verkopen",
    "nav_btn_register": "Registreren",
    "commonall_resultpage_tag_pending": "In behandeling",
    "commonall_enterfield_title_total": "Totaal",
    "nav_okxalert_app_btn_download": "Openen",
    "commonall_enterfield_title_type": "Type",
    "nav_menu_btn_demo_trading": "Demohandel",
    "nav_dex_dropdown_item_auto_translate_x_content": "X-inhoud vertalen",
    "nav_dropdown_copy_trading_desc": "Jouw toegangspoort tot topkeuzes en spannende kansen",
    "nav_dialog_body_gotowallet": "Je verlaat OKX Exchange nu en wordt doorgestuurd naar OKX Wallet. Houd er rekening mee dat je gebruik van het OKX Wallet-platform onderworpen is aan aparte algemene voorwaarden en dat de OKX-entiteit die je diensten levert op het OKX Exchange-platform niet verantwoordelijk is voor enige inhoud of diensten op het OKX Wallet-platform.",
    "nav_perpetual_navigation_tab_meme_pump": "Meme Pump",
    "nav_country_banner_content_us": "Het lijkt erop dat je in de {country} bent. Schakel over naar de {country} site voor producten die in jouw regio beschikbaar zijn.",
    "nav_web3_header_nav_btn_app_store": "App Store",
    "navdropdown_header_textarea_purchase_guidance": "Volg stapsgewijze instructies om crypto te kopen",
    "nav_title_tools": "Krachtige tools",
    "nav_desc_institutions_insights": "Ons laatste institutionele handelsonderzoek, nieuws en meer",
    "nav_title_market_maker_portal": "Marktmaker-portal",
    "commonall_modal_btn_claim": "Claimen",
    "commonall_modal_btn_more": "Meer",
    "nav_language_dropdowntitle_language": "Taal",
    "nav_investhome_mid_modaltitle_region_unavailable": "Dit OKX Web3-product is niet beschikbaar in jouw regio"
};