window['okx_web_wallet'] = 
{
    "wallet_testnet_icon_name_x": "X",
    "wallet_popup_title_current_eth_gas_new": "Huidige gas {coinName}",
    "commonall_dropdown_text_other": "Overig",
    "wallet_connect_popup_tab_okx_app_connect": "Koppelen met de OKX Wallet-app",
    "commonall_emptystate_text_no_data": "Geen gegevens beschikbaar",
    "wallet_search_top_tab_1": "Top zoekopdrachten",
    "wallet_profile_title_vote_rule_update": "Likes worden in real time geüpdatet en de positie wordt dagelijks om 18:00 uur vernieuwd (UTC+8).",
    "wallet_modal_connectwallet_rainbow": "Rainbow",
    "commonall_enterfield_title_name": "Naam",
    "wallet_settings_input_enter_note": "Voer een notitie in om het adres gemakkelijk te identificeren",
    "wallet_home_common_variable_days_singular_plural": "{num, plural, =1 {{num} day} other {{num} days}}",
    "commonall_text_title_time": "Tijd",
    "wallet_faucets_title_obtain_answer": "Verbind je OKX Wallet, kies een geschikt testnet, tik op “Claim” en voltooi de vereiste taken.",
    "wallet_card_text_not_downloadyet": "Heb je de app niet?",
    "commonall_enterfield_title_address": "Adres",
    "wallet_faucets_error_insufficient_balance": "Onvoldoende saldo",
    "commonall_btn_title_contact_us": "Contact met ons opnemen",
    "metax_modal_connectwallet_extensions_metamask": "MetaMask",
    "wallet_function_radio_num_selected_page": "Alle {num} op deze pagina zijn geselecteerd",
    "wallet_transfer_error_entered_key_add": "Voer de private key en het ontvangstadres in.",
    "wallet_trade_alert_title_dust_convert_failed": "Kan niet converteren",
    "wallet_function_nav_btn_copy_address": "Adres kopiëren",
    "commonall_status_text_expired": "Vervallen",
    "wallet_transfer_title_transfer_all": "3. Alles overschrijven",
    "wallet_collection_title_you_can_receive": "Je kunt ontvangen",
    "wallet_transfer_error_invalid_address": "Ongeldig adres. Controleer het en voer het opnieuw in.",
    "commonall_column_colheader_rank": "Positie",
    "commonall_datetime_abbr_hour": "u",
    "wallet_info_label_agent_url": "URL van agent",
    "wallet_popup_bottom_link_terms_of_service": "Servicevoorwaarden",
    "commonall_tag_text_fixed": "Vast",
    "commonall_enterfield_btn_deposit": "Storten",
    "wallet_card_tag_ended": "Afgelopen",
    "commonall_enterfield_title_to": "Naar",
    "wallet_home_short_day_pnl_variable": "{num}D PnL",
    "wallet_extension_describe_connect_crypto_wallet": "Verbinding maken met crypto-wallet",
    "wallet_kol_title_changemaker": "2024 Web3 Pionier",
    "wallet_search_title_top_searches": "Top zoekopdrachten",
    "header_okc_btn_wallet": "Koppel wallet",
    "wallet_solana_title_read_official": "Hoe kan ik meer informatie vinden over Solana?",
    "wallet_profile_title_earn_reward": "Hoe kun je beloningen claimen?",
    "wallet_manage_text_notes": "Aantekeningen",
    "wallet_trade_alert_title_switch_browser_app": "Gebruik de desktopbrowser of mobiele app",
    "wallet_fractal_desc_check_reward": "Beloningen beschikbaar",
    "okx_web_account_home_btn_close": "Sluiten",
    "commonall_enterfield_text_please_enter": "Alsjeblieft invoeren",
    "commonall_emptystate_text_page_500_button": "OKX-app downloaden",
    "wallet_nav_tab_dapp": "DApp",
    "wallet_auto_confirm_sa_notice_auto_confirm_cannot_be_turned_off": "Automatisch bevestigen kan niet worden uitgezet in smart accounts.",
    "wallet_auto_confirm_update_extension_notice": "Update je OKX Wallet-extensie om deze functie te gebruiken.",
    "wallet_search_tab_dapp": "DApps",
    "wallet_collection_title_explore_more": "Meer verkennen",
    "wallet_dapp_disclaimer_body_external_site_tos": "OKX Wallet ondersteunt on-chain interacties via directe bezoeken van DApp-websites. Zorg ervoor dat je de authenticiteit ervan verifieert om je bezittingen veilig te houden. Door verder te gaan, ga je akkoord met onze {tos}.",
    "commonall_btn_text_try_again": "Opnieuw proberen",
    "metaxets_deposit_modal_text_receive_address": "Ontvangend adres",
    "metax_modal_connnectwallet_tooltip_evminclude": "Ondersteunt momenteel: {network}",
    "commonall_filter_title_transactions": "Transacties",
    "metax_top_notif_confirm_connection_on_wallet": "Bevestig de koppeling via de extensie",
    "commonall_resultpage_toast_canceled": "Geannuleerd",
    "commonall_filter_title_history": "Geschiedenis",
    "wallet_common_toast_info_copied": "Gegevens gekopieerd",
    "wallet_login_dialog_wallet_management": "Walletbeheer",
    "pr_wallet_dapp_okx_web_wallet": "Webversie OKX",
    "wallet_discover_title_discover_ai_agents": "De {agent}-toekomst begint hier",
    "metax_mid_btn_cancel": "Annuleren",
    "wallet_header_tab_other_wallet": "Anders",
    "commonall_emptystate_text_no_results": "Geen resultaten gevonden",
    "metax_header_wallet_modal_title_my_wallet": "Wallets",
    "wallet_profile_desc_earn_reward": "De resultaten worden bekendgemaakt op {day} {month} om {time} (UTC+8). De influencers die hebben gewonnen, moeten een rechtstreeks bericht versturen naar @{accountName} met hun bezorgadres om beloning te claimen.",
    "wallet_assets_converter_faq_answer_small_assets": "Alle verhandelbare digitale bezittingen op OKX DEX met een saldo tussen 0,001 en 10 USD.",
    "commonall_modal_btn_connect_wallet": "Portemonnee verbinden",
    "commonall_enterfield_toast_canceled": "Geannuleerd",
    "commonall_colheader_text_txn_hash": "Txn-hash",
    "wallet_trade_alert_desc_dust_convert_failed": "Dust converter is tijdelijk niet beschikbaar. Probeer het later opnieuw.",
    "wallet_search_tab_all": "Alle",
    "wallet_trade_tooltips_convert_after_completion": "Wacht tot deze conversie is voltooid voordat je een nieuwe start.",
    "commonall_resultpage_btn_save": "Opslaan",
    "wallet_account_status_subtitle_auto_renewing": "Automatische verlenging",
    "wallet_transfer_error_insufficient_balance": "Onvoldoende saldo.",
    "home_header_nav_dropdown_more_copyaddress_toast_success": "Gekopieerd",
    "commonall_search_fieldtext_search": "Zoeken",
    "wallet_popup_title_current_btc_fee": "Huidige BTC-vergoeding",
    "commonall_enterfield_title_email": "E-mail",
    "wallet_placeorder_radio_select_max": "Alles selecteren (max. 50)",
    "commonall_enterfield_btn_refresh": "Vernieuwen",
    "wallet_discover_search_agent_name": "Zoek op naam of ID van agent",
    "commonall_colheader_text_operator": "Operator",
    "wallet_assets_converter_faq_text_solana_recovery": "Verhuurde Solana terugvorderen",
    "wallet_login_dialog_dashboard": "Dashboard",
    "wallet_function_dialog_desc_high_network_fee": "Je ontvangt bij deze conversie minder dan wat je betaalt in kosten. Weet je zeker dat je wilt doorgaan?",
    "wallet_discover_table_score": "Score",
    "wallet_solana_input_label_account_name": "Tokenaccount die moet worden afgesloten",
    "commonall_enterfield_btn_verify": "Verifiëren",
    "metax_card_btn_connect": "Verbinden",
    "wallet_function_dialog_btn_continue_trade": "Toch doorgaan",
    "wallet_transfer_title_send_exchange_account": "Naar Exchange-account versturen",
    "commonall_button_btn_submit": "Indienen",
    "wallet_header_dialog_current_connection": "Huidige wallet",
    "commonall_column_tab_available": "Beschikbaar",
    "wallet_top_subtitle_enjoy": "Begin veilig aan je Web3 reis",
    "wallet_transfer_title_enter_key": "1. Voer je private key in",
    "wallet_search_tooltips_low_liquidity": "Lage liquiditeit",
    "wallet_general_colheader_amount": "Bedrag",
    "wallet_poster_header_placeholder_assessing": "Beleef je Web3-reis van 2025 opnieuw",
    "wallet_function_dialog_btn_solana_rent_recovery": "Solana-huur herstellen",
    "commonall_btn_text_transfer": "Overschrijving",
    "wallet_transfer_dialog_btn_transfer_all": "Alles overschrijven",
    "wallet_faucets_btn_view_more": "Meer weergeven",
    "commonall_tag_text_flexible": "Flexibel",
    "wallet_kol_title_personality": "Opmerkelijkste persoon van 2024",
    "wallet_testnet_icon_name_discord": "Discord",
    "test": "test",
    "wallet_fractal_tab_connect_wallet": "Je OKX Wallet koppelen",
    "commonall_resultpage_tag_failed": "Mislukt",
    "commonall_button_title_faq": "Veelgestelde vragen",
    "commonall_title_item_text_withdrawal": "Opname",
    "commonall_emptystate_text_page_404_button": "Ga naar de startpagina",
    "wallet_placeorder_trade_label_service_fee": "Servicevergoeding",
    "commonall_colheader_title_amount": "Bedrag",
    "wallet_feedback_badge_feedback_count": "{num, plural, =1 {# feedback} other {# feedbacks}}",
    "wallet_trade_notification_txn_submitted": "Transactie ingediend",
    "wallet_collection_title_snapshot_time": "Tijdstip van de snapshot",
    "commonall_emptystate_text_try_again": "Opnieuw proberen",
    "wallet_info_title_offchain_metadata": "Metagegevens van offchain",
    "wallet_collection_subtitle_starts_in": "Begint over",
    "wallet_faucets_tab_connect_okx": "Je OKX Wallet koppelen",
    "commonall_btn_title_filter": "Filteren",
    "wallet_collection_your_receiving_address": "Je ontvangstadres",
    "wallet_overview_title_services": "Diensten",
    "commonall_text_btn_confirm": "Bevestigen",
    "commonall_modal_btn_approve": "Goedkeuren",
    "commonall_modal_label_available_balance": "Beschikbaar saldo",
    "commonall_filter_btn_deposit": "Storten",
    "wallet_login_dialog_preference": "Voorkeuren",
    "wallet_general_emptystate_btn_refresh": "Vernieuwen",
    "wallet_info_label_created_tx": "Transactie aanmaken",
    "wallet_watchonly_popup_title_watch_only": "Watch-only wallet",
    "wallet_info_title_timestamps": "Tijdstempels",
    "wallet_function_year_review_qr_deeplink": "okxwallet://wallet/miniapp?appid=Web3AnnualReport&pageurl=/web3annual&appearance=alternativeweb3&pageanim=present&StatusBarStyle=1&theme=dark&minversion=2.0.2",
    "wallet_discover_card_networks": "Netwerken",
    "wallet_faucets_desc_address_answer": "Elk netwerkadres kan tot 3 wallet-adressen koppelen om tokens te claimen.",
    "commonall_resultpage_btn_edit": "Bewerken",
    "metax_card_btn_install": "Extensie toevoegen",
    "wallet_solana_error_no_available_recovery": "Deze account heeft geen tokens die kunnen worden geclaimd.",
    "wallet_search_toast_contract_address_copied": "Contractadres is gekopieerd",
    "commonall_resultpage_button_verifying_task": "Verifying",
    "commonall_filter_dropdown_trade": "Handelen",
    "wallet_function_dialog_title_conversion_completed": "Voltooid",
    "wallet_account_status_label_enabled": "Ingeschakeld",
    "commonall_colheader_text_token": "Token",
    "commonall_filter_dropdown_custom": "Aangepast",
    "wallet_stats_title_overview": "Overzicht van statistieken",
    "wallet_memefi_link_number": "2.0.6",
    "okx_web_account_home_text_refresh_qr_code": "Nieuwe QR code genereren",
    "metax_modal_title_connectwallet": "Wallet koppelen",
    "wallet_dashboard_toast_watchonly_added": "Toegevoegd",
    "wallet_trade_bttmsheet_label_total_amount": "Totaalbedrag",
    "commonall_emptystate_text_page_404_subtitle": "We konden niet vinden wat je zocht, maar op onze homepage vind je wel wat je zoekt.",
    "wallet_pricelist_alert_num_tokens_noquotes": "{num, plural, =1 {Kan # token zonder koers niet converteren.} other {Kan # tokens zonder koers niet converteren.}}",
    "commonall_text_btn_share_discord": "Discord",
    "wallet_memefi_btn_okx_on_telegram": "OKX Wallet op Telegram openen",
    "wallet_transfer_error_calculation_fail": "Berekening mislukt.",
    "commonall_emptystate_text_no_records": "Geen records gevonden",
    "wallet_transfer_reminder_title_confirm_transfer": "Overschrijving bevestigen",
    "wallet_kol_drawer_vote_rule": "Wat zijn de regels voor stemmen?",
    "commonall_enterfield_title_currency": "Valuta",
    "wallet_manage_title_edit_watch_wallet": "Watch-only wallet bewerken",
    "wallet_account_status_subtitle_renew_in_time": "Verleng over {time}",
    "metaxets_topnotif_toast_wallet_reach_upper_limit": "Je hebt de limiet voor het toevoegen van wallets bereikt",
    "commonall_modal_title_overview": "Overzicht",
    "wallet_connectwallet_popup_title_phantom": "Phantom",
    "commonall_text_btn_view_details": "Details weergeven",
    "wallet_search_colheader_1h_turnover": "Volume 1u",
    "wallet_transfer_reminder_desc_confirm_transfer": "Door te bevestigen schrijf je al je eigen tokens over, behalve die voor de netwerkvergoeding. Controleer of het ontvangende adres juist is.",
    "wallet_faucets_desc_testnet_answer": "Een testnetfaucet voorziet je van testnet-tokens voor het inzetten, testen en optimaliseren van smart contracts op testnetwerken.",
    "wallet_faucets_error_unable_reconnect_faucet": "Kan het wallet-adres niet verkrijgen. Schakel over naar een seed phrase wallet of gebruik de webversie.",
    "wallet_placeorder_trade_renew_sa": "Smart account activeren",
    "commonall_filter_title_price": "Prijs",
    "commonall_modal_btn_subscribe": "Abonneren",
    "commonall_datetime_abbr_second": "s",
    "wallet_transfer_mid_value_est_netfee": "Geschatte netwerkvergoeding: {estfee}",
    "metaxets_header_add_modal_errortip_incorrect_address": "Verkeerd adres. Controleer en voer opnieuw in.",
    "commonall_enterfield_btn_close": "Sluiten",
    "commonall_colheader_text_to": "Naar",
    "commonall_column_tab_pnl": "PnL%",
    "wallet_stats_label_last_updated": "Laatst geüpdatet",
    "wallet_home_profile_btn_tooltip_follow": "Volgen",
    "commonall_enterfield_title_wallet": "Portemonnee",
    "wallet_discover_narrow_title_discover_ai_agents": "The Truth Layer for\n{agent}",
    "commonall_modal_title_fee": "Vergoeding",
    "commonall_column_colheader_assets": "Activa",
    "wallet_info_label_contract_state": "Contractgegevens",
    "support_msg_test_publish": "hallo wereld",
    "wallet_transfer_cell_label_account_num": "Accountnummer:",
    "commonall_filter_btn_delete": "Verwijderen",
    "commonall_enterfield_title_last_price": "Laatste prijs",
    "commonall_text_label_tab_trading_account": "Handelsaccount",
    "wallet_profile_title_vote_rule_connect": "Elk X-account kan aan meerdere wallets in OKX Wallet gekoppeld worden. Elk netwerkadres kan maximaal 3 wallet-adressen koppelen.",
    "wallet_placeorder_select_label_num_selected": "{num} geselecteerd",
    "wallet_transfer_error_init_add_format": "Onjuiste indeling. Het adres moet een geldige bech32-indeling hebben.",
    "commonall_enterfield_title_buy": "Kopen",
    "wallet_stats_label_total_feedback": "Totale feedbacks",
    "wallet_placeorder_trade_label_minimum_received": "Minimaal te ontvangen",
    "wallet_dapp_disclaimer_title_external_site": "Je bezoekt een externe website",
    "commonall_button_text_send": "Versturen",
    "wallet_auto_confirm_cta_button_ok": "OK",
    "wallet_popup_link_learn_more": "Meer informatie",
    "commonall_enterfield_text_amount_ccy": "Bedrag",
    "commonall_colheader_text_action": "Handeling",
    "commonall_text_payment_method": "Betalingsmethode",
    "metaxets_header_text_scan_code_deposit": "Scan de QR-code om {crypto} te ontvangen",
    "wallet_discover_header_erc8004_scanner": "8004-scanner van OKX",
    "wallet_pnl_checkbox_hide_risky_token": "Verberg risicovolle tokens",
    "wallet_discover_narrow_input_search": "Zoeken",
    "wallet_faucets_tab_testnet_token": "Alles geclaimd",
    "wallet_discover_card_active_7d": "Actieve agenten (7D)",
    "wallet_popup_connectwallet_keplr": "Keplr",
    "wallet_card_btn_install_now": "Toevoegen",
    "commonall_enterfield_title_crypto": "Crypto",
    "commonall_emptystate_text_page_404_title": "Deze pagina kan niet worden uitgehasht",
    "wallet_okx_web_domain": "https://www.okx.com",
    "wallet_poster_header_mission_debrief": "Missieoverzicht: {expedition}",
    "wallet_function_regularcell_grouptitle_more_events": "Meer evenementen",
    "wallet_info_label_registry_info": "Registergegevens",
    "commonall_modal_title_type": "Type",
    "wallet_kol_search_placeholder_id_or_name": "Zoek op de naam van de Influencer of X gebruikersnaam",
    "commonall_button_text_done": "Klaar",
    "metax_list_item_okx_wallet": "OKX Wallet",
    "wallet_assets_converter_faq_small_assets": "Wat kwalificeert er als dust?",
    "wallet_connectwallet_list_phantom": "Phantom",
    "commonall_tab_text_nft": "NFT",
    "wallet_popup_title_keplr": "Keplr",
    "wallet_solana_input_label_wallet_address": "Wallet-adres",
    "wallet_share_dialog_header_share": "Airdrop delen",
    "metax_modal_connnectwallet_input_noresults_found": "Geen resultaten gevonden",
    "wallet_discover_dropdowns_tab_all": "Alle",
    "wallet_popup_btn_confirm": "Bevestigen",
    "commonall_enterfield_btn_max": "Max",
    "wallet_discover_table_rank": "Rang",
    "wallet_login_popup_scan_pending": "Bevestig op je app",
    "commonall_tag_text_new": "Nieuw",
    "wallet_header_tab_watch_only_wallet": "Watch-only wallet",
    "commonall_text_btn_tab_buy": "Koop",
    "wallet_info_label_created": "Aangemaakt",
    "commonall_tab_tag_dropdown_spot": "Spot",
    "wallet_account_status_subtitle_renew_by_date": "Tot {date}",
    "wallet_auto_confirm_bottom_dialog_skip_manual_confirmation": "Schakel 'Automatisch bevestigen' in om je markt- en limietorders niet meer handmatig te hoeven ondertekenen.",
    "commonall_text_btn_view": "Bekijken",
    "wallet_assets_converter_faq_answer_eligibility": "De converter is alleen beschikbaar voor smart accounts. Voeg een smart account toe of schakel deze in om te beginnen. Als je geavanceerde handelsfuncties zoals dust converter gebruikt, moet je OKX Wallet koppelen en op ‘Smart account inschakelen’ klikken. Ga vervolgens verder door de instructies te volgen. Je kunt dit ook doen door direct naar de pagina met accountgegevens in je OKX Wallet te gaan.",
    "wallet_transfer_cell_label_add": "Adres:",
    "wallet_transfer_cell_label_transferable": "Overschrijfbaar bedrag:",
    "wallet_kol_title_community_contributor": "Bijdrager community van 2024",
    "commonall_text_btn_view_more": "Meer bekijken",
    "wallet_placeorder_emptystate_title_no_tokens_available": "Geen tokens beschikbaar",
    "wallet_faucets_tab_balance_usd": "Meer dan 10 USD aan walletsaldo hebben",
    "wallet_placeorder_trade_btn_unlock_convert": "Smart account activeren",
    "wallet_general_emptystate_subtitle_loading_fail": "Er ging iets mis. Probeer het later opnieuw.",
    "wallet_function_tooltips_extra_bonus": "Basisbedrag: {amount}. Je komt ook in aanmerking voor de OKX Wallet gebruikersbonus.",
    "wallet_extension_popup_title_wallet_connect": "WalletConnect",
    "wallet_home_common_short_months_singular_plural": "{num}M",
    "commonall_resultpage_btn_delete": "Verwijderen",
    "wallet_card_text_download_again": "Voeg nu toe",
    "wallet_discover_dropdown_all_networks": "Alle netwerken",
    "commonall_modal_title_reminder": "Herinnering",
    "commonall_modal_title_price": "Prijs",
    "wallet_profile_title_vote_rule_time": "Het stemmen begint op {startDay} {startMonth} om {startTime} (UTC+8) en eindigt op {endDay} {endMonth} om {endTime} (UTC+8).",
    "wallet_faucets_desc_second": "{second} s",
    "wallet_faucets_banner_available": "Beschikbaar: {amount} {token}",
    "wallet_share_dialog_label_starts_at": "Begint over {time}",
    "wallet_solana_title_where_sol": "Huur terugvorderen van Solana-account?",
    "commonall_label_colheader_tab_mark_price": "Markeerprijs",
    "commonall_enterfield_btn_submit": "Indienen",
    "commonall_resultpage_btn_add": "Toevoegen",
    "metax_header_subtitle_metaxdesc": "We hebben vastgesteld dat je de OKX Wallet-extensie niet hebt geïnstalleerd.",
    "wallet_transfer_dialog_btn_confirm_key": "Private key bevestigen",
    "wallet_solana_error_not_support_recovery": "Deze wallet ondersteunt Solana niet. Probeer het met een andere wallet.",
    "wallet_placeorder_trade_label_slippage": "Prijsverschuiving",
    "commonall_button_text_previous": "Vorige",
    "metax_mid_text_watchonly_plztyping": "Voer wallet-adres of domeinnaam in om de bezittingen en transactiegeschiedenis ervan te bekijken.",
    "wallet_popup_type_send": "Versturen",
    "wallet_popup_title_select_network": "Netwerk selecteren",
    "wallet_popup_title_evmnetwork": "Netwerken die compatibel zijn met EVM",
    "wallet_assets_converter_faq_whats_converter": "Wat is de dust converter?",
    "metaxets_defiplugin_modal_text_install_already": "Heb je de wallet-extensie al geïnstalleerd? ",
    "wallet_function_dialog_header_txn_status": "Transactiestatus",
    "wallet_faucets_banner_start_time": "Start over {time}",
    "wallet_extension_text_click_refresh_qrcode": "Klik om de QR-code te vernieuwen",
    "wallet_card_title_install_explorer": "OKX Wallet-extensie op {name}",
    "commonall_column_tab_fees": "Vergoedingen",
    "wallet_transfer_cell_label_bal": "Saldo:",
    "commonall_column_tab_addresses": "Adressen",
    "commonall_enterfield_btn_trade": "Handelen",
    "wallet_transfer_error_balance_fee_higher": "Je saldo is {asset}. De netwerkvergoeding is {fee}. Om een overschrijving te doen, moet je saldo hoger zijn dan de netwerkvergoeding.",
    "commonall_resultpage_toast_copied": "Gekopieerd",
    "commonall_column_tab_options": "Opties",
    "commonall_label_title_date_of_birth": "Geboortedatum",
    "wallet_placeorder_emptystate_desc_try_again_later": "Probeer het later opnieuw.",
    "wallet_solana_notification_header_submit": "Huurterugvordering ingediend",
    "commonall_enterfield_btn_copy_link": "Link kopiëren",
    "commonall_modal_btn_trade": "Handelen",
    "wallet_login_dialog_toolkit": "Toolkit",
    "wallet_transfer_action_btn_send_assets": "Bezittingen versturen",
    "wallet_card_tag_upcoming": "Aanstaand",
    "wallet_assets_converter_faq_answer_supported_networks": "De tool ondersteunt momenteel alleen Solana. Ondersteuning voor andere EVM-netwerken wordt in de komende weken toegevoegd.",
    "wallet_assets_converter_tooltips_dust_slippage": "Bij het gebruik van een dust converter worden je prijsverschuivingsinstellingen individueel toegepast op de tokenswaps die in de conversie zijn opgenomen. Indien een individuele swap je prijsverschuiving overschrijdt, wordt deze geannuleerd zonder terugbetaling van de netwerkkosten. Dit heeft geen invloed op andere swaps.",
    "wallet_discover_feedbacks_emptystate_no_feedback": "Geen feedback verstrekt",
    "wallet_kol_title_creative": "2024 Web3 Creatieve leider",
    "commonall_filter_btn_save": "Opslaan",
    "wallet_account_status_label_disabled": "Uitgeschakeld",
    "wallet_assets_converter_faq_supported_networks": "Welke netwerken worden ondersteund?",
    "commonall_filter_dropdown_earn": "Earn",
    "wallet_assets_converter_faq_learn_sa": "Waar vind ik meer informatie over smart accounts?",
    "wallet_transfer_toast_desc_transfer_success": "Over te schrijven bedrag: {amount}. Netwerkvergoeding: {fee}. Tx-hash: {txhash}.",
    "wallet_transfer_error_invalid_add_reason": "Ongeldig ontvangstadres: {reason}",
    "metax_modal_connnectwallet_evm_supportednow": "Ondersteunt {num}+ EVM-netwerken",
    "commonall_button_text_next": "Volgende",
    "commonall_colheader_label_remarks": "Opmerkingen",
    "metax_header_support_check_gasfees": "Gaskosten controleren",
    "wallet_info_label_agent_id": "Agent-ID",
    "technology_publish_all_1741336743982": "test",
    "commonall_enterfield_title_instrument": "Instrument",
    "wallet_auto_confirm_update_extension_notice_update_now_redirect": "Meer informatie",
    "metaxets_header_add_modal_errortip_wallet_extist": "Wallet bestaat al",
    "commonall_text_btn_edit": "Bewerken",
    "wallet_conncect_xverse_text_connected_xverse": "Xverse",
    "commonall_text_colheader_description": "Beschrijving",
    "commonall_enterfield_title_price": "Prijs",
    "commonall_column_colheader_funding_account": "Financieringsrekening",
    "wallet_login_popup_app_version": "(Versie 6.96.0 of later is vereist)",
    "wallet_transfer_error_init_add_length": "Onjuiste lengte. Het adres moet 43 tekens lang zijn. Het huidige adres heeft {num} tekens.",
    "wallet_share_dialog_footer_okx_wallet": "OKX Wallet",
    "wallet_search_input_label_you_may_search": "Wil je zeggen:",
    "wallet_kol_title_content_creator": "De beste maker van inhoud van 2024",
    "commonall_datetime_abbr_month": "M",
    "wallet_overview_btn_view_all": "Alles bekijken ({num})",
    "wallet_charts_pill_7d": "7d",
    "metax_modal_connnectwallet_input_search": "Zoeken",
    "wallet_general_dialog_btn_cancel": "Annuleren",
    "commonall_modal_title_account": "Rekening",
    "wallet_search_colheader_24h_turnover": "24u volume",
    "metaxets_deposit_modal_desc_deposit_network": "Verzend alleen assets van het {network}-netwerk naar dit adres. ",
    "wallet_transfer_toast_desc_transfer_fail": "Overschrijving mislukt: {error}",
    "wallet_search_toast_address_copied": "Adres gekopieerd",
    "wallet_placeorder_trade_btn_convert": "Converteren",
    "wallet_faucets_subtitle_other_faucet": "Overige faucets",
    "wallet_transfer_cell_label_est_netfee": "Geschatte netwerkvergoeding:",
    "wallet_faucets_tag_evm": "EVM",
    "wallet_connect_popup_tab_mini_wallet": "Koppelen met Mini-Wallet",
    "wallet_fractal_desc_transactions": "2. Ten minste 3 keer in de afgelopen 6 maanden Ordinals, Runes of Atomicals hebben verhandeld op OKX Web3 Marktplaats.",
    "commonall_modal_title_network": "Netwerk",
    "wallet_popup_title_how_much": "Hoeveel heb ik nodig?",
    "commonall_tab_btn_swap": "Swap",
    "commonall_text_btn_tab_sell": "Verkoop",
    "metax_signup_modal_trackaddress_btn_add": "Bevestigen",
    "wallet_poster_header_recap_2025_expedition": "Beleef je Web3-reis van 2025 opnieuw",
    "wallet_discover_table_link": "Website",
    "wallet_extension_assets_dialog_desc_order_progress": "Wacht tot de huidige order is voltooid voordat je een nieuwe start.",
    "wallet_trade_alert_desc_okx_seed_phrase": "Dust converter is niet beschikbaar voor je huidige wallet. Schakel over op een seed phrase wallet in OKX Wallet en schakel een smart account in om deze functie te ontgrendelen.",
    "commonall_timeformat_title_to": "Naar",
    "commonall_label_text_est_apr": "Gesch. APR",
    "wallet_popup_tag_connect_wallet_phantom_btc": "Phantom BTC",
    "commonall_modal_btn_settings": "Instellingen",
    "wallet_manage_text_optional": "(optioneel)",
    "wallet_home_popup_title_access_restricted": "Toegang beperkt",
    "wallet_popup_title_how_much1": "Hoeveel heb ik nodig?",
    "wallet_card_title_connect_wallet_extension": "OKX Wallet-extensie",
    "wallet_gastracker_text_failed_try": "Kan de gegevens niet laden. Probeer nog eens.",
    "commonall_resultpage_title_processing": "Bezig met verwerken",
    "commonall_filter_title_market_cap": "Marktlimiet",
    "wallet_solana_btn_claiming_recovery": "Claimen",
    "wallet_solana_header_title_token_account": "Verhuurde Solana terugvorderen",
    "commonall_modal_btn_deposit": "Storten",
    "wallet_transfer_mid_value_balance": "Saldo: {balance}",
    "commonall_resultpage_btn_more": "Meer",
    "wallet_faucets_finish_all_task": "Voltooi taken en claim beloningen",
    "wallet_login_popup_btn_retry": "Opnieuw proberen",
    "okx_web_account_home_text_gas_tracker": "Gas-tracker",
    "wallet_search_btn_show_more": "Meer weergeven",
    "wallet_solana_desc_where_sol": "Zodra je de ongebruikte Solana-accounts sluit, krijg je de SOL die je voor de huur hebt gebruikt terug. Zorg ervoor dat er geen tokens of NFT's meer op die accounts staan.",
    "wallet_aptos_tooltip_desc_compatible_network": "Je adres is een Aptos-netwerkadres. Je kunt het gebruiken om je bezittingen op andere Aptos-compatible netwerken te beheren.",
    "wallet_transfer_dialog_title_confirm_transfer_info": "Bevestig de gegevens van de overschrijving",
    "commonall_modal_title_rewards": "Beloningen",
    "wallet_account_status_title_smart_account": "Slimme rekening",
    "commonall_text_btn_cancel": "Annuleren",
    "commonall_emptystate_text_no_internet": "Geen internetverbinding",
    "wallet_dialog_header_switch_seed_phrase_wallet": "Schakel over naar een seed phrase-wallet",
    "wallet_faucets_desc_obtain_answer": "Je moet minstens 10 USD aan tokens in je OKX Wallet hebben. \nJe kunt elke paar uur testnet tokens claimen. De vereisten kunnen per testnet verschillen.",
    "wallet_function_dialog_text_received_amt": "Ontvangen op: {amt}",
    "wallet_collection_label_num_countdown": "{day} D {hour} u {min} m",
    "wallet_dapp_disclaimer_checkbox_no_prompt_next": "Niet meer weergeven bij het bezoeken van externe websites",
    "wallet_info_label_owner": "Eigenaar",
    "wallet_fractal_desc_btc_balance": "1. Meer dan 100 USD aan BTC bezitten in je OKX Wallet vanaf 00:00 (UTC+8) op 1 sep.",
    "wallet_popup_tooltip_evminclude": "EVM-compatibele ondersteunde netwerken: {network}",
    "wallet_transfer_error_capital_add": "Adres mag geen hoofdletters bevatten.",
    "wallet_activity_filter_tag_all_time": "Totaal",
    "wallet_info_label_name": "Naam",
    "wallet_popup_type_trade": "Handelen",
    "wallet_faucets_desc_claim_question": "Wat zijn de vereisten voor het claimen van testnet tokens?",
    "wallet_faucets_reminder_desc_delay_receive": "De tokens kunnen met enige vertraging aankomen op je account. Hartelijk dank voor je geduld.",
    "wallet_general_title_faq": "Veelgestelde vragen",
    "metax_modal_connectwallt_othermethod_trackaddress": "Alleen kijken",
    "wallet_popup_text_priority": "Prioriteit: {number}",
    "wallet_card_btn_installed_connecting": "Bezig met koppelen",
    "commonall_modal_btn_continue": "Doorgaan",
    "wallet_placeorder_emptystate_desc_connect_wallet": "Je kunt het proberen met een andere wallet.",
    "commonall_modal_btn_buy_crypto": "Crypto kopen",
    "commonall_resultpage_btn_download": "Downloaden",
    "wallet_solana_input_label_total_sol": "Totaal te claimen huur",
    "wallet_info_title_onchain_metadata": "Onchain metadata",
    "commonall_filter_title_type": "Type",
    "wallet_assets_converter_faq_answer_converter_work": "Selecteer de tokens die je wilt converteren, onderteken de transactie en je smart account voert de transactie uit tegen de best beschikbare prijs. Je ontvangt de geconverteerde eigen tokens rechtstreeks in je wallet. Als je Solana-bezit converteert, kun je bovendien onze {link} gebruiken om extra SOL te claimen.",
    "wallet_trade_notification_title_num_tokens_converted": "{num, plural, =1 {# token geconverteerd} other {# tokens geconverteerd}}",
    "wallet_top_notification_desc_some_dust_coverted": "{num} tokens omgezet naar {amt} {token}",
    "wallet_info_label_registry": "Register",
    "wallet_profile_title_vote_rule_ban": "Het manipuleren van stemmen is verboden en kan tot diskwalificatie leiden. De uiteindelijke positie wordt gebaseerd op de door OKX Wallet bekendgemaakte resultaten. OKX Wallet behoudt zich het recht voor interpretatie van dit evenement.",
    "wallet_header_tab_okx_wallet": "OKX Wallet",
    "wallet_transfer_error_init_add_invalid_char": "Ongeldige tekens gevonden. Het bech32-adres mag geen deze tekens bevatten: 1, b, i, o.",
    "wallet_function_dialog_title_high_network_fee": "Ongunstige vergoeding",
    "wallet_memefi_desc_scan_telegram": "Scan deze code om OKX Wallet op Telegram te openen of selecteer {telegram}",
    "commonall_button_text_share": "Delen",
    "commonall_emptystate_text_page_500_subtitle": "Als er niet snel een consensus wordt bereikt, vernieuw je de pagina of neem je contact op via {support}.",
    "wallet_search_list_text_pnl_calculation_chain": "De PnL van dit adres houdt alleen rekening met zijn bezittingen op {chainId}.",
    "wallet_auto_confirm_status_off": "Gedeactiveerd",
    "commonall_filter_btn_apply": "Toepassen",
    "commonall_column_tab_network_fee": "Netwerkvergoeding",
    "wallet_overview_tab_feedback": "Feedbacks",
    "wallet_testnet_icon_name_telegram": "Telegram",
    "okx_web_account_home_text_loading": "Laden",
    "wallet_placeorder_trade_alert_receive_low": "U ontvangt minder dan wat je aan kosten betaalt.",
    "wallet_placeorder_trade_subheader_to": "Ontvang",
    "wallet_profile_title_vote_rule_like": "Stemmen is alleen beschikbaar voor EVM-adressen en elk wallet-adres kan maar één like geven.",
    "wallet_fractal_desc_fractal_introduction": "Fractal Bitcoin is de enige oplossing voor het opschalen van Bitcoin die de Bitcoin Core-code zelf gebruikt om ongelimiteerd lagen te gebruiken bovenop 's werelds veiligste en meest gebruikte blockchain.",
    "wallet_faucets_notification_title_insufficient_faucet": "Het saldo van je testnet token is onvoldoende",
    "wallet_faucets_title_testnet_question": "Wat is een testnetfaucet?",
    "wallet_login_dialog_history": "Geschiedenis",
    "wallet_stats_time_last_update": "{num}m geleden",
    "metax_mid_btn_try_again": "Opnieuw proberen",
    "commonall_colheader_title_symbol": "Symbool",
    "wallet_function_dialog_text_network_fee_amt": "Netwerkvergoeding: {amt}",
    "commonall_resultpage_title_status": "Status",
    "wallet_placeorder_trade_label_est_network_fee": "Geschatte netwerkvergoeding",
    "wallet_popup_toast_info_update_every_sec": "Deze informatie wordt elke {num} seconden bijgewerkt.",
    "metax_mid_modaltitle_connect_failed": "Koppelen mislukt",
    "wallet_discover_table_network": "Netwerk",
    "metax_top_notif_wallet_disconnected": "Wallet is ontkoppeld",
    "commonall_text_tag_yes": "Ja",
    "commonall_enterfield_title_token": "Token",
    "commonall_text_link_terms_of_service": "Servicevoorwaarden",
    "wallet_connectwallet_popup_phantom_desc": "We hebben vastgesteld dat de Phantom-extensie niet is geïnstalleerd.",
    "commonall_text_contract_address": "Contractadres",
    "metax_modal_connectwallet_scantoconnect_walletconnect": "WalletConnect",
    "commonall_colheader_text_actions": "Handelingen",
    "commonall_text_colheader_or": "of",
    "wallet_faucets_tag_btc": "BTC",
    "wallet_general_hyperlink_explorer": "Controleren op Explorer",
    "wallet_function_dialog_desc_convert_after_completion": "Je kunt deze pagina verlaten tijdens de conversie. Houd er rekening mee dat je slechts één conversie tegelijk kunt starten.",
    "wallet_placeorder_select_subheader_hidden_tokens": "Kan niet converteren",
    "commonall_toast_text_copied": "Gekopieerd",
    "wallet_fractal_tab_title_verification": "Controleren of je in aanmerking komt",
    "commonall_btn_tab_text_mint": "Minten",
    "wallet_pricelist_alert_no_quote_token": "Kan dit token niet converteren omdat er geen koers werd gevonden.",
    "wallet_common_time_days_ago": "{num}d geleden",
    "wallet_discover_table_feedback": "Feedbacks",
    "wallet_overview_empty_label_no_feedback": "Geen feedback beschikbaar",
    "wallet_card_text_appqr_scan": "1. Ga naar wallet homepage\n2. Selecteer Meer en kies Scannen",
    "metax_header_title_metamask": "MetaMask",
    "wallet_collection_label_num_countdown_hms": "{hour}u {minute}m {second}s",
    "wallet_transfer_title_header_oktc_transfer": "OKT Chain bezit overschrijven",
    "wallet_search_placeholder_token_add_dapp": "Token, adres of DApp zoeken",
    "wallet_extension_one_interoperable_wallet_for_all": "Eén interoperabele wallet voor al je Web3-behoeften",
    "commonall_filter_btn_add": "Toevoegen",
    "commonall_btn_text_reject": "Verwerpen",
    "wallet_auto_confirm_turned_on_coachmark_des": "Je kunt dit op elk moment deactiveren in de instellingen van je wallet.",
    "wallet_solana_desc_token_account": "Huur terugvorderen met rekeningadressen voor eenvoudiger beheer van bezittingen.",
    "metaxets_connect_errortip_refresh_reconnect": "De pagina wordt automatisch vernieuwd. Verbind je wallet opnieuw na het vernieuwen.",
    "metaxets_appscan_application_name": "OKX Wallet",
    "wallet_search_tab_tokens": "Tokens",
    "wallet_connect_text_immutable_passport": "Onveranderbaar paspoort",
    "wallet_account_status_label_not_enabled": "Niet ingeschakeld",
    "commonall_title_tab_language": "Taal",
    "wallet_popup_text_base": "Basis: {number}",
    "metax_header_title_watchonly": "Voer adres of domeinnaam in",
    "wallet_placeorder_header_dust_converter": "Dust converter",
    "commonall_text_btn_ok_active": "OK",
    "commonall_modal_btn_withdraw": "Opnemen",
    "wallet_faucets_title_address_question": "Waarom kan ik met mijn huidige netwerkadres geen testnet tokens claimen met mijn wallet?",
    "commonall_text_btn_back": "Terug",
    "wallet_header_nav_desc_connect_wallet": "Eenvoudig het potentieel van onchain ontgrendelen",
    "wallet_faucets_connected_wallet": "Gekoppeld: {address}",
    "commonall_button_add_to_favorites": "Toevoegen aan favorieten",
    "commonall_filter_btn_download": "Downloaden",
    "wallet_transfer_toast_title_transfer_success": "Overschrijving gelukt",
    "commonall_filter_dropdown_perpetual": "Eeuwigdurend",
    "wallet_overview_title_agent_leaderboard": "Agent scorebord",
    "commonall_filter_dropdown_spot": "Spot",
    "wallet_faucets_available_token_num": "Beschikbaar: {amount} {token}",
    "wallet_memefi_btn_wallet_app": "De OKX Wallet-app openen",
    "wallet_memefi_desc_scan_telegram_icu": "Telegram Desktop",
    "commonall_modal_btn_apply": "Toepassen",
    "wallet_transfer_error_enter_key": "Je moet een private key invoeren.",
    "commonall_filter_title_name": "Naam",
    "wallet_general_dialog_btn_done": "Klaar",
    "commonall_button_text_start": "Beginnen",
    "wallet_trade_notification_title_conversion_unsuccessful": "Conversie mislukt",
    "wallet_kol_desc_countdown_result": "Resultaten worden over {day}d {hour}u {minute}m{second}s, aangekondigd",
    "wallet_solana_desc_what_is_recovery": "Op het Solana-netwerk heeft elke token of NFT een aparte account. Deze accounts vereisen een storting van SOL als huur om actief te blijven.",
    "commonall_datetime_abbr_minute": "m",
    "wallet_trade_notification_desc_reinitiate_txn": "Probeer de transactie opnieuw te starten.",
    "wallet_general_emptystate_connect_try": "Koppel wallet en probeer het opnieuw.",
    "wallet_assets_emptystate_connect_wallet_first": "Koppel eerst je wallet",
    "commonall_button_text_view_all": "Alles bekijken",
    "wallet_placeorder_subheader_dust_converter": "Converteer bezittingen met een lage waarde op Solana in één keer om naar SOL. Binnenkort beschikbaar voor andere netwerken.",
    "wallet_auto_confirm_learn_more_redirect": "Meer informatie",
    "wallet_header_nav_asset_management": "Bezittingen",
    "wallet_search_colheader_market_cap": "Marktkapitalisatie",
    "commonall_datetime_abbr_year": "Y",
    "wallet_function_dialog_title_conversion_num_fail": "{num, plural, =1 {# swap is mislukt} other {# swaps zijn mislukt}}",
    "commonall_filter_btn_transfer": "Overschrijven",
    "wallet_extension_assets_dialog_title_order_progress": "Order in uitvoering",
    "commonall_resultpage_title_details": "Details",
    "wallet_extension_toast_address_copied": "{network}-adres is gekopieerd",
    "wallet_kol_desc_event_end": "Het evenement is beëindigd.",
    "wallet_assets_intro_tee_signing_message": "De transactie die je uitvoert wordt gevalideerd en automatisch ondertekend binnen de vertrouwde uitvoeringsomgeving.",
    "wallet_nav_tab_info": "Informatie",
    "wallet_transfer_mid_value_transfer_amt": "Over te schrijven bedrag: {transferamt}",
    "commonall_column_tab_all": "Alle",
    "wallet_assets_converter_faq_answer_wallet_sa": "Als je geavanceerde handelsfuncties zoals dust converter gebruikt, moet je OKX Wallet koppelen en op ‘Smart account inschakelen’ klikken. Volg dan de instructies om verder te gaan. Je kunt dit ook doen door direct naar de pagina met accountgegevens in je OKX Wallet te gaan.",
    "wallet_account_toast_error_sa_network_issue": "Kan de status van het smart account niet controleren vanwege netwerkproblemen. Probeer het opnieuw of ga naar accountgegevens in de extensie.",
    "wallet_charts_pill_1mon": "1 miljoen",
    "commonall_filter_btn_edit": "Bewerken",
    "wallet_discover_btn_dapp": "DApp",
    "commonall_colheader_text_from": "Van",
    "commonall_filter_dropdown_select": "Selecteren",
    "wallet_function_cell_error_no_price": "Geen prijs gevonden",
    "wallet_aptos_tab_title_compatible_network": "Netwerken die compatibel zijn met Aptos",
    "commonall_column_tab_receive": "Ontvangen",
    "wallet_search_emptystate_no_results": "Geen resultaten gevonden",
    "wallet_function_dialog_title_conversion_failed": "Conversie mislukt",
    "wallet_transfer_mid_value_receiving_add": "Ontvangstadres: {toaddress}",
    "metax_modal_connnectwallet_evmnetwork": "EVM-netwerken",
    "commonall_filter_btn_reset": "Opnieuw instellen",
    "wallet_transfer_error_no_transfer_assets": "Je hebt geen overschrijfbare bezittingen.",
    "commonall_text_btn_ok_passive": "OK",
    "wallet_card_text_not_setyet": "Nog niet toegevoegd?",
    "wallet_stats_label_average_score": "Gem. gebruikersscore",
    "wallet_placeorder_select_subheader_from": "Betaal",
    "wallet_function_tooltips_extra_bonus_false": "Basisbedrag: {amount}. Je komt niet in aanmerking voor de OKX Wallet-gebruikersbonus.",
    "wallet_share_dialog_footer_check_airdrop": "Controleer je airdrop-toewijzing",
    "commonall_modal_btn_log_in": "Inloggen",
    "wallet_popup_text_evm_supportednow": "We ondersteunen nu {num}+ netwerken die compatibel zijn met EVM",
    "commonall_enterfield_text_quantity": "Aantal",
    "wallet_connect_popup_tab_okx_app": "Ervaring in de OKX Wallet-app",
    "wallet_transfer_error_confirm_key_first": "Bevestig de private key om accountgegevens op te halen.",
    "commonall_datetime_abbr_week": "W",
    "wallet_home_common_variable_months_singular_plural": "{num, plural, =1 {{num} month} other {{num} months}}",
    "wallet_assets_converter_faq_converter_work": "Hoe werkt de dust converter?",
    "wallet_memefi_title_airdrop_checker": "MemeFi Airdrop-controleur",
    "metaxets_connect_errortip_connected": "Wallet is gekoppeld",
    "wallet_search_tab_addresses": "Adressen",
    "commonall_filter_btn_select_all": "Alles selecteren",
    "metaxets_top_toast_logout_disconnect": "Ontkoppelen",
    "commonall_enterfield_btn_transfer": "Overschrijven",
    "wallet_popup_tag_connect_wallet_btc": "Bitcoin",
    "wallet_solana_tooltips_multi_transaction_close_account": "Als je meer dan 24 accounts sluit, worden verschillende transacties gestart om het terugvorderen van de huur te voltooien.",
    "wallet_collection_title_prerequisites": "Vereisten",
    "commonall_filter_btn_apply_search": "Toepassen",
    "commonall_enterfield_title_balance": "Saldo",
    "metax_modal_connnectwallet_extensions_metax": "OKX Wallet",
    "wallet_card_btn_check_details": "Gegevens bekijken",
    "wallet_main_desc_web_test_tokens": "Ontdek testnet-tokens in de populairste Web3-ecosystemen op één plek",
    "wallet_card_textbtn_click_download": "Downloaden",
    "wallet_faucets_title_claim_question": "Hoe kun je testnet tokens claimen?",
    "wallet_login_dialog_approvals": "Goedkeuringen",
    "wallet_charts_pill_3mon": "3 miljoen",
    "wallet_kol_title_dedicated": "Kampioen betrokkenheid van 2024",
    "metaxets_top_notif_connect_success": "Wallet is gekoppeld",
    "wallet_gastracker_btn_try_again": "Opnieuw proberen",
    "wallet_conncect_unisat_item_connect_unisat": "UniSat",
    "wallet_general_colheader_token": "Token",
    "metax_card_tag_new": "V2.0",
    "wallet_header_nav_asset_dashboard": "Dashboard",
    "commonall_column_colheader_operation": "Bewerking",
    "home_header_nav_dropdown_more_copyaddress": "Adres kopiëren",
    "wallet_assets_converter_faq_wallet_sa": "Hoe zet ik mijn wallet-account om in een smart account?",
    "wallet_function_radio_select_all_page": "Selecteer alles op deze pagina",
    "wallet_popup_tag_connect_wallet_solana": "Solana",
    "commonall_column_tab_pool": "Pool",
    "wallet_trade_tag_convert_progress": "Conversie wordt verwerkt",
    "wallet_placeorder_trade_connect_sa": "Wallet koppelen",
    "commonall_modal_btn_transfer": "Overschrijven",
    "wallet_card_btn_connect": "Verbinden",
    "wallet_discover_card_total_agents": "Totaal aantal agenten",
    "wallet_discover_table_agent": "Agent",
    "wallet_discover_card_activities": "Interacties",
    "commonall_text_title_share_telegram": "Telegram",
    "commonall_datetime_abbr_day": "D",
    "wallet_search_colheader_name": "Naam",
    "wallet_kol_title_trailblazer": "Crypto pionier van 2024",
    "commonall_enterfield_text_buy": "Stad",
    "wallet_transfer_error_no_account_info": "Kan accountgegevens niet ophalen.",
    "commonall_placeholder_text_please_select": "Maak een selectie",
    "wallet_function_general_radio_select_all": "Alles selecteren",
    "wallet_fractal_title_meet_criteria": "Opstartprogramma voor het Mainnet",
    "wallet_transfer_toast_hyperlink_check_explorer": "Controleren op Explorer",
    "wallet_placeorder_trade_fill_up_token": "Onvoldoende {token}-saldo",
    "wallet_trade_notification_desc_amt_token_received": "Je hebt {amt} {token} ontvangen",
    "wallet_search_tooltips_community_recognized": "Door de community erkend",
    "wallet_function_dialog_title_converting_num_tokens": "{num, plural, =1 {Bezig met converteren van # token} other {Bezig met converteren van # tokens}}",
    "metaxets_header_text_change_wallet": "Wallet wisselen",
    "wallet_home_common_short_days_singular_plural": "{num}D",
    "commonall_filter_dropdown_futures": "Aflopend",
    "wallet_auto_confirm_name_status": "Autobevestig",
    "wallet_trade_alert_desc_seed_phrase": "Dust converter is niet beschikbaar voor je huidige wallet. Schakel over naar een seed phrase wallet en schakel een smart account in om deze functie te ontgrendelen.",
    "commonall_modal_title_total": "Totaal",
    "commonall_text_tag_no": "Nee",
    "wallet_trade_alert_desc_switch_browser_app": "Deze functie is niet beschikbaar op mobiele browsers. Je kunt er via een desktopbrowser of met onze mobiele app toegang tot verkrijgen.",
    "wallet_transfer_emptystate_title_unsupported_address": "Het huidige adres wordt niet ondersteund",
    "wallet_home_profile_btn_tooltip_unfollow": "Ontvolgen",
    "wallet_fractal_tab_top_active_user": "Top 5.000 actieve gebruikers in het OKX Wallet BTC ecosysteem",
    "wallet_assets_converter_faq_answer_text_faq": "Veelgestelde vragen",
    "wallet_faucets_notification_desc_test_token_send": "De faucet verwerkt je claim en verstuurt je testnet-tokens naar: {address}",
    "wallet_search_dialog_textbtn_all_networks": "Alle netwerken",
    "metax_modal_connnectwallet_tooltip_evmnetwork": "Je adres bevindt zich op het EVM-netwerk en je kunt ook assets van andere EVM-netwerken beheren",
    "wallet_function_nav_btn_trade": "Handelen",
    "wallet_info_label_agent_wallet": "Agent-wallet",
    "wallet_share_dialog_label_i_receive": "Ik kan ontvangen",
    "wallet_assets_converter_faq_answer_learn_sa": "Lees voor meer informatie de {faq} over smart accounts.",
    "wallet_kol_send_x_message": "#OKXInfluencers✨ Boost de toekomst van Web3 - stem op je favoriete influencers met OKX!",
    "wallet_home_popup_access_restricted_describe": "Producten of diensten van okx.com zijn niet beschikbaar in je regio ({area}) vanwege de plaatselijke wet- en regelgeving.",
    "wallet_overview_tab_overview": "Overzicht",
    "wallet_transfer_error_balance_fee_insufficient": "Je saldo is {asset}. De netwerkvergoeding is {fee}. Je hebt niet genoeg saldo om een overschrijving te doen.",
    "wallet_collection_input_tips_address_unavailable_switch": "Geen adressen beschikbaar. Probeer naar een andere wallet over te schakelen.",
    "metax_header_title_petrawallet": "Petra Wallet",
    "wallet_search_placeholder_name_address": "Crypto, adres, DApp",
    "commonall_tab_dropdown_margin": "Marge",
    "wallet_main_title_web_testnet_faucets": "Testnet faucets",
    "wallet_transfer_error_empty_add": "Adres mag niet leeg zijn.",
    "wallet_discover_table_label_unnamed": "Geen naam {idnum}",
    "wallet_transfer_enter_init_add": "Voer het ontvangstadres in (bijv. init1...)",
    "commonall_emptystate_text_page_500_variate": "support@okx.com",
    "wallet_kol_title_influencial": "Meest invloedrijke personen van 2024",
    "wallet_kol_title_outstanding": "Buitengewone beïnvloeder van 2024",
    "commonall_resultpage_btn_close": "Sluiten",
    "wallet_memefi_desc_airdrop_checker": "OKX Wallet werkt samen met MemeFi om te verifiëren of je in aanmerking komt om MEMEFI-tokens te claimen.",
    "wallet_search_title_search_history": "Zoekgeschiedenis",
    "wallet_general_error_title_service_unavailable": "Service niet beschikbaar",
    "wallet_transfer_error_add_format_correct": "Adresindeling correct",
    "commonall_resultpage_tag_canceled": "Voltooid",
    "wallet_placeorder_trade_label_est_priority_fee": "Gesch. prioriteitsvergoeding",
    "wallet_login_dialog_portfolio": "Portfolio",
    "wallet_faucets_desc_claim_left": "{timeNum, plural, =1 {# claim resterend} other {# claims resterend}}",
    "wallet_solana_desc_read_official_icu": "Solana-documentatie",
    "wallet_trade_alert_title_switch_wallet": "Een andere wallet selecteren",
    "wallet_transfer_error_init_add_head": "Adres moet beginnen met init1.",
    "commonall_enterfield_title_from": "Van",
    "commonall_filter_dropdown_others": "Overigen",
    "metax_header_subtitle_metamaskdesc": "Je hebt de MetaMask-extensie nog niet geïnstalleerd.",
    "wallet_general_emptystate_title_loading_fail": "Kan deze pagina niet laden",
    "wallet_solana_input_placeholder_token_name": "SOL",
    "wallet_stats_label_trust_score": "Totale score",
    "metaxets_connect_errortip_connect_failed_try_again": "Tijdens het koppelen is er iets misgegaan. Probeer het opnieuw.",
    "wallet_kol_send_x_message_domain": "https://twitter.com/intent",
    "wallet_faucets_notification_title_claimed_faucet": "Verzoek om te claimen ingediend",
    "wallet_share_dialog_input_placeholder": "Doe met me mee en bekijk je {project}-airdrop 🔥",
    "commonall_status_tab_tag_ended": "Afgelopen",
    "wallet_faucets_reminder_title_claim_submitted": "Claim ingediend",
    "metax_mid_modaldesc_connect_failed": "WalletConnect-verbinding is instabiel. Scan opnieuw om verbinding te maken.",
    "commonall_filter_title_free": "Gratis",
    "wallet_poster_header_subtitle_scan_start_review": "Scan met je OKX-app om te beginnen",
    "commonall_column_tab_order_id": "Order-ID",
    "wallet_info_label_chain": "Netwerk",
    "wallet_transfer_cell_label_sequence_num": "Volgordenummer:",
    "wallet_kol_title_main_page_kol": "Belangrijkste Web3 influencers",
    "wallet_aptos_tab_desc_compatible_network": "We ondersteunen nu {num}+ netwerken die compatibel zijn met Aptos",
    "commonall_enterfield_toast_copied": "Gekopieerd",
    "wallet_login_dialog_pnl_analysis": "PnL-analyse",
    "metax_card_btn_trying_connect": "Wallet koppelen",
    "commonall_title_placeholder_select_network": "Netwerk selecteren",
    "commonall_filter_title_volume": "Volume",
    "wallet_transfer_placeholder_enter_exchange_receiving_address": "Voer het ontvangstadres van je Exchange-account in",
    "commonall_modal_btn_copy": "Kopiëren",
    "wallet_kol_desc_kol_event_end": "Evenement eindigt over {day}D {hour}u {minute}m {second}s",
    "wallet_search_colheader_liquidity": "Liquiditeit",
    "commonall_enterfield_title_user_id": "Gebruikers-ID",
    "metaxets_connect_modal_title_web3_connect": "Tik om verbinding te maken",
    "wallet_gastracker_text_failed_load": "Laden mislukt",
    "wallet_faucets_btn_claim_in_time_faucet": "Over {time} claimen",
    "commonall_emptystate_text_page_500_title": "Er ging iets buiten de chain",
    "wallet_pricelist_select_textbtn_hidden_tokens": "{num, plural, =1 {Kan (#) niet converteren} other {Kan (#) niet converteren}}",
    "commonall_modal_btn_done": "Klaar",
    "commonall_colheader_text_unit_price": "Eenheidsprijs",
    "wallet_transfer_title_account_info": "2. Accountgegevens",
    "wallet_poster_bot_btn_begin_debrief": "Begin debrief",
    "metax_header_title_metax": "OKX Wallet",
    "wallet_search_colheader_price": "Prijs",
    "commonall_timeformat_title_date": "Datum",
    "wallet_popup_tooltip_evmnetwork": "Je adres is een EVM-netwerkadres. Je kunt het gebruiken om je bezittingen op andere EVM-compatible netwerken te beheren.",
    "commonall_modal_btn_i_understand": "Ik begrijp het",
    "wallet_transfer_toast_notification_token_send_success": "{amttoken} is verstuurd",
    "commonall_timeformat_title_from": "Van",
    "wallet_discover_title_discover_variable_agent": "AI Agents",
    "wallet_overview_title_feedback": "Feedbacks",
    "wallet_common_time_mins_ago": "{num}m geleden",
    "commonall_btn_title_modify": "Bewerken",
    "wallet_extension_popup_text_connetting_agree": "Door te koppelen met OKX Wallet, ga je akkoord met de {service} van OKX Web3",
    "wallet_faucets_emptystate_load_data_failed": "Kan de gegevens niet laden. Probeer later nog eens.",
    "wallet_card_title_okx_walletapp": "OKX-app",
    "commonall_text_label_share_x": "X",
    "wallet_connect_tab_mini_wallet": "Mini Wallet",
    "wallet_placeorder_trade_converting": "Converteren",
    "commonall_label_title_term": "Termijn",
    "wallet_search_tooltips_risky_token": "Risicovol token",
    "wallet_popup_type_nft": "NFT-markt",
    "commonall_btn_text_show_less": "Minder weergeven",
    "wallet_trade_bttmsheet_header_order_confirmation": "Orderbevestiging",
    "commonall_text_btn_learn_more": "Meer informatie",
    "wallet_extension_general_dialog_btn_check_order": "Orders controleren",
    "wallet_home_short_month_pnl_variable": "{num}M PnL",
    "wallet_popup_title_keplr_desc": "We hebben vastgesteld dat de Keplr-extensie niet is geïnstalleerd.",
    "wallet_fractal_title_fractal_bitcoin_mainnet": "Fractal Bitcoin Mainnet",
    "wallet_transfer_placeholder_enter": "Invoeren",
    "wallet_common_time_hrs_ago": "{num}u geleden",
    "wallet_search_emptystate_desc_token_not_found": "Geen resultaten gevonden voor {token1}. Wilde je naar {token2} zoeken?",
    "commonall_btn_text_verify": "Verifiëren",
    "wallet_discover_table_tooltips_no_dapp_site": "Deze agent heeft geen officiële website.",
    "wallet_search_toast_history_deleted": "Zoekgeschiedenis verwijderd",
    "metax_card_btn_connecting": "Bezig met koppelen",
    "wallet_solana_desc_read_official": "Raadpleeg de officiële {documentation}.",
    "wallet_auto_confirm_turned_on_coachmark_header": "Aut. bevestigen aan",
    "commonall_resultpage_tag_expired": "Vervallen",
    "commonall_modal_text_insufficient_balance": "Onvoldoende saldo",
    "wallet_function_dialog_desc_refresh_retry": "Ga terug naar de conversiespagina en probeer het opnieuw.",
    "commonall_enterfield_title_sell": "Verkopen",
    "wallet_overview_empty_label_no_services": "Geen diensten beschikbaar",
    "commonall_resultpage_tag_pending": "In behandeling",
    "commonall_enterfield_title_total": "Totaal",
    "wallet_manage_text_address": "Adres",
    "commonall_enterfield_title_type": "Type",
    "wallet_solana_title_what_is_recovery": "Informatie over Solana-accounthuur?",
    "wallet_kol_title_rising_star": "Crypto-opkomende ster van 2024",
    "wallet_assets_converter_faq_eligibility": "Hoe kom ik in aanmerking voor het converteren van kleine bezittingen?",
    "wallet_account_dialog_desc_seed_phrase_sa": "Smart accounts zijn alleen beschikbaar voor seed phrase-walletaccounts (exclusief TON-wallets).",
    "wallet_card_tag_ongoing": "Actief",
    "wallet_faucets_emptystate_btn_retry": "Opnieuw proberen",
    "wallet_kol_title_social_media": "Visionair sociale media van 2024",
    "wallet_assets_converter_faq_answer_whats_converter": "Met de dust converter swap je kleine tokensaldi voor de eigen tokens van netwerken in één transactie. Elke verhandelbare digitale bezitting op OKX DEX met een saldo tussen 0,001 en 10 USD wordt beschouwd als dust.\n\nOpmerking: Deze functie ondersteunt op dit moment alleen Solana. Ondersteuning voor andere EVM-netwerken wordt in de komende weken toegevoegd.",
    "wallet_testnet_icon_name_website": "Officiële website",
    "wallet_assets_title_header_oktc_assets": "OKT Chain-bezittingen",
    "wallet_transfer_status_btn_sending": "Versturen",
    "wallet_status_txt_last_active": "Laatst actief: {num}",
    "commonall_modal_btn_claim": "Claimen",
    "commonall_modal_btn_more": "Meer",
    "wallet_info_title_basic_information": "Basisgegevens",
    "wallet_auto_confirm_status_on": "Geactiveerd"
};